// <auto-generated />

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using PetSupport.Infrastructure.Data.Data;

namespace PetSupport.Infrastructure.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    internal class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("PetSupport.Core.Entities.BookingMessage", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .UseIdentityColumn();

                b.Property<int>("ClientId")
                    .HasColumnType("int");

                b.Property<int>("PetsitterId")
                    .HasColumnType("int");

                b.Property<string>("Text")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.HasIndex("ClientId");

                b.HasIndex("PetsitterId");

                b.ToTable("BookingMessages");

                b.HasData(
                    new
                    {
                        Id = 1,
                        ClientId = 30,
                        PetsitterId = 36,
                        Text =
                            "Omnis deserunt consequatur quia incidunt suscipit voluptatem nihil. Et et voluptas omnis et aut. Ut vel ut iure delectus eum quibusdam omnis assumenda et. Deserunt culpa asperiores eum beatae saepe culpa cumque quo et. Non corporis ipsam et.\n\nHic eaque alias accusantium ab provident molestiae. Voluptas consequuntur eligendi vel autem aliquam aliquid qui iusto. Voluptas iure fugit omnis rerum velit. Quae architecto facere ducimus. Architecto aliquid et ut animi qui et officiis perspiciatis ab.\n\nEnim assumenda rerum quia ipsa libero et. Accusamus necessitatibus est adipisci. In explicabo et consequatur consequatur blanditiis.\n\nQuo illo laboriosam in natus. Dolorum incidunt natus rerum temporibus voluptatem ut labore. Enim eveniet alias voluptate."
                    },
                    new
                    {
                        Id = 2,
                        ClientId = 8,
                        PetsitterId = 57,
                        Text =
                            "Culpa est temporibus sed. Optio et ut deserunt eveniet non voluptatum quo. Maxime atque perferendis dolore delectus enim alias.\n\nEt nesciunt sint quos voluptates alias ab quis aut. Accusamus omnis ut assumenda qui maiores sed quos ut. Nihil sit voluptas laudantium. Voluptatem occaecati qui rerum veniam maxime dolor mollitia minus. Ipsa quisquam sed sequi ut perspiciatis est aspernatur optio nulla. Omnis quo error quaerat et qui expedita repellendus qui.\n\nQui qui omnis deleniti et est. Aperiam est dolorem ut necessitatibus voluptate voluptatem sit suscipit. Et vel incidunt quasi dolorum reiciendis quis aut fugiat. Pariatur molestiae cupiditate consequatur minima corporis. Ut voluptatum qui inventore saepe a enim distinctio.\n\nPerspiciatis dolorem sequi repellat aut corrupti at. Rerum nisi voluptas fugiat. Reprehenderit tempore qui enim voluptatibus aut dolorem ex."
                    },
                    new
                    {
                        Id = 3,
                        ClientId = 18,
                        PetsitterId = 59,
                        Text =
                            "At itaque placeat omnis vero sapiente voluptate laudantium ea dolorem. Cum vel maxime iusto tempore tempore rerum sapiente voluptatem iusto. Alias iure quasi est nostrum omnis doloribus voluptatem. Labore qui alias magnam unde aut autem. Eum sint quis reprehenderit error eligendi ratione necessitatibus ut. Dolores nobis enim fuga odio natus consequuntur itaque.\n\nIpsum tempore vero voluptatum explicabo ut quod veniam. Dolores necessitatibus similique exercitationem eos in. Et suscipit odio optio et quibusdam. Debitis quos culpa.\n\nTenetur dignissimos quia laborum quod est laborum. Veritatis saepe exercitationem voluptas hic et excepturi id. Non iure qui quae eaque dolores temporibus et nam. Quis et reiciendis maiores excepturi a quia voluptas recusandae.\n\nDolorem est dolore et nisi. Eaque aut maxime inventore. Voluptatem explicabo error adipisci dolorem. Sint rerum suscipit fugit architecto et labore."
                    },
                    new
                    {
                        Id = 4,
                        ClientId = 3,
                        PetsitterId = 33,
                        Text =
                            "Quis dolorem sed in commodi excepturi odit omnis sed. Optio voluptas placeat iure. Impedit sunt exercitationem rerum quam voluptatem magni iste voluptate doloribus. Neque placeat est. Voluptas quaerat quaerat. Quod et occaecati nihil tenetur.\n\nEsse dolorum iure modi dolorum qui. Sequi numquam voluptatem et velit corrupti laudantium labore. Magni officia voluptas ut ex. Velit esse iusto. Dolores est alias.\n\nNisi corporis delectus ut molestias ipsum. Consequatur blanditiis iusto deserunt. At delectus inventore est temporibus et.\n\nSed fuga ut aut sit nihil. Repellendus iste sunt beatae sequi doloremque assumenda blanditiis eveniet cupiditate. Minus aut earum eius officiis repudiandae voluptas. Nisi qui vel exercitationem nihil ratione aliquid. Voluptatem porro quasi et sunt dicta velit in vel."
                    },
                    new
                    {
                        Id = 5,
                        ClientId = 11,
                        PetsitterId = 41,
                        Text =
                            "Dicta excepturi neque dolore tempora assumenda. Ducimus ut facere voluptatem suscipit porro beatae. Voluptate voluptatem eum non et labore quas. Eum distinctio asperiores est ut perspiciatis ea molestias.\n\nDolorem quaerat itaque numquam quae. Vel aut nisi commodi delectus placeat. At consequatur nobis asperiores omnis voluptatibus molestiae. Non culpa est suscipit officia incidunt quia facilis. Dolores dolore omnis aut omnis qui in consectetur numquam et.\n\nSaepe qui est beatae dolores eos rerum eius omnis at. Magni est a soluta dolorem aut praesentium. Quaerat nesciunt iusto accusamus. Doloribus sint corporis amet odit et suscipit beatae. Rerum ipsam odio repellat quaerat qui explicabo deleniti molestiae ex.\n\nEt quia mollitia qui velit enim possimus expedita. Quo praesentium ad illo dicta. Quo blanditiis fugit placeat sint qui aliquam. Rerum et ipsum. Consequatur sequi dolor minus vitae modi alias."
                    },
                    new
                    {
                        Id = 6,
                        ClientId = 6,
                        PetsitterId = 41,
                        Text =
                            "Optio corrupti culpa. Qui et vero neque earum ipsum. Quaerat voluptatem ipsam id magni ut quis ad tenetur. Labore est facere et excepturi aut autem ab illo est. Consequuntur velit quam voluptatem itaque doloremque.\n\nRepellendus beatae tempora qui. Eveniet possimus quam deleniti. Minus doloribus et. Ratione blanditiis et dolorem sint architecto optio deleniti fugit. Ducimus velit magni est eveniet nisi adipisci labore cumque accusantium.\n\nPerferendis ut qui id facere nobis eveniet tenetur voluptatem. Quas quis ut sapiente praesentium aut aut animi. Corporis sapiente laboriosam consequatur facere assumenda voluptatem.\n\nUt dolores nostrum saepe. Quia dignissimos similique labore ipsam voluptatem perferendis. Nesciunt similique quo voluptates possimus laboriosam recusandae. Vitae magni aspernatur deleniti eos vero tempore tempora eum quo. Neque possimus illo dolorem odio est repellendus."
                    },
                    new
                    {
                        Id = 7,
                        ClientId = 16,
                        PetsitterId = 59,
                        Text =
                            "Autem minima sed quisquam aut est exercitationem voluptas aut. Officia aliquam illum commodi adipisci velit est laudantium assumenda. Velit voluptatum porro pariatur dolorem. Quod ad corporis. Qui velit doloribus non suscipit qui rerum qui illo ut. Maiores eum autem in quas ut laudantium dolore adipisci inventore.\n\nOmnis praesentium ipsam error nobis saepe cumque aperiam voluptatem. Aperiam esse dolor voluptatem id doloremque quis. Qui velit accusamus ea nihil est. Enim voluptatem et minima accusantium odit sint repudiandae distinctio iusto.\n\nAliquam quaerat dolore. Et repudiandae ducimus autem vel. Labore et et officiis qui rem. Rerum voluptatem eaque. Rerum esse sunt fugiat facere asperiores iusto sed. Occaecati dolorem at aut sed quia.\n\nAlias quos aut. Perspiciatis officiis vitae ut nulla voluptatem autem dignissimos nulla. Quis quo aliquid laborum nulla tempore occaecati fugit sint. Tempore debitis aut."
                    },
                    new
                    {
                        Id = 8,
                        ClientId = 24,
                        PetsitterId = 43,
                        Text =
                            "Cupiditate magni aut aut expedita veritatis consequatur aspernatur ut. Mollitia voluptates voluptas inventore tempore et. Ut qui expedita quas ea libero ut necessitatibus. Delectus sit nam asperiores libero praesentium nihil.\n\nIpsam quo saepe et est perspiciatis excepturi corporis dolor. Sed beatae tenetur alias tempora eos officiis harum voluptas aliquam. Laudantium totam asperiores dicta. Fuga iusto unde.\n\nCorrupti ducimus quia ea. Pariatur voluptates quos fugit doloribus illo corrupti dolorum nobis. Aut sit iusto at autem eum. Qui est pariatur consequatur ut ut omnis sint. Possimus aliquid dolor. Harum placeat rerum velit quis sapiente eos est.\n\nReiciendis pariatur nemo. Sunt dignissimos repellat eligendi aperiam nemo eum. Sint excepturi ducimus hic consequatur. Velit voluptates ullam eos quo delectus et voluptatem ut accusantium."
                    },
                    new
                    {
                        Id = 9,
                        ClientId = 25,
                        PetsitterId = 47,
                        Text =
                            "Debitis qui officiis. Deserunt hic laudantium rem beatae veritatis voluptatem. Rerum voluptas ut magni sapiente laboriosam. Velit qui aliquid consequatur voluptas aut laboriosam. Dolorem ut aut consequuntur sed et dolorem molestiae.\n\nNon ea quam deleniti est fugiat ut illum. Vitae sed accusantium velit veritatis. Labore quos omnis cupiditate. Doloremque molestias magnam eius quidem sunt odit itaque sed. Inventore ut corporis corrupti aperiam voluptatibus quia porro est. Sunt voluptatem est quaerat consectetur quibusdam corrupti.\n\nSapiente consequuntur enim ut sequi est quam odit velit nulla. Est ullam optio quas. Quidem est et. Dolore et omnis. Consequatur sed aut vero doloribus doloremque quo vitae velit. Sequi minus temporibus.\n\nAut laborum officiis aut. In autem ad quia qui ut omnis architecto error. Et eveniet ut dignissimos saepe tenetur animi natus fugit ipsum. Et non quaerat. Est ut rerum culpa ipsa quam quis. Et magnam non."
                    },
                    new
                    {
                        Id = 10,
                        ClientId = 21,
                        PetsitterId = 58,
                        Text =
                            "Voluptatum omnis sint voluptatem eum aliquam eum nisi odit. Veniam ab possimus et. Molestias ut sit dolor consequatur alias repudiandae quos cupiditate. Veniam aut dignissimos adipisci soluta doloremque. Nulla ea optio dolore omnis quia debitis quis reprehenderit necessitatibus.\n\nPossimus consequatur laborum nostrum ipsa maxime. Voluptates et ut facere natus enim asperiores eos aut qui. Voluptatem nihil nesciunt consequatur sed in odit et a inventore. Quos aut aut vel. Assumenda sunt libero.\n\nDucimus id quia aut dolores est. Reiciendis iste ut est. Blanditiis quod aut tempora iure neque numquam sit nihil. Necessitatibus assumenda velit autem rerum sit neque modi est. Recusandae provident nihil est eaque ea.\n\nAut rerum in quo consequatur expedita occaecati quis enim. Vel molestiae qui sit reiciendis expedita nulla ex mollitia quia. Tenetur vel suscipit sunt suscipit ut et eaque nihil consectetur. Blanditiis nihil non. Reprehenderit dolor in possimus at ut repudiandae quis voluptas."
                    },
                    new
                    {
                        Id = 11,
                        ClientId = 30,
                        PetsitterId = 56,
                        Text =
                            "Quae voluptas nobis omnis officia qui voluptatem. Veritatis eos doloremque facere mollitia suscipit nulla nobis aliquid. Accusantium sed adipisci ut libero a. Ut optio ipsa cupiditate quos est aliquid ullam consequatur. Qui molestias ut accusamus animi consectetur a voluptas eaque consequatur.\n\nRecusandae et id quos vel. Atque ea dolor ipsum est et voluptatem quia voluptatibus corporis. Velit cum blanditiis tempora nisi voluptatem dolor.\n\nNihil molestiae labore itaque harum officia voluptas. Voluptas aut sint. Ut qui vel aut non velit dolor ut omnis voluptatum.\n\nFacere fuga est unde doloremque deserunt et molestiae. Dolor provident iste sed voluptas ut. Beatae enim ea consequatur."
                    },
                    new
                    {
                        Id = 12,
                        ClientId = 18,
                        PetsitterId = 42,
                        Text =
                            "Rerum numquam magni pariatur qui. Ab hic porro qui sit consequatur ut exercitationem. Quia ipsum quos mollitia similique et aliquam saepe quis officiis.\n\nLabore sed quia ut sit. Voluptate et vel praesentium hic doloremque nam. Qui voluptas provident expedita provident ut repellendus sit. Fugiat necessitatibus reiciendis et. Iure quia omnis reiciendis facere voluptatum.\n\nMolestias voluptatem alias ducimus dolores iure neque quo eius. Recusandae quo veniam velit ea quo. Voluptate deleniti voluptates non quis. Sed inventore doloribus occaecati quos cumque. Ad amet et facere sit numquam et dicta quod qui. Voluptatum et molestiae quae.\n\nAut delectus quae rerum. Asperiores ut ut eos earum. Iure quas accusamus tempore perferendis dolore amet maxime repudiandae. Beatae qui inventore magnam nam vitae quod. Possimus hic nesciunt qui at unde."
                    },
                    new
                    {
                        Id = 13,
                        ClientId = 20,
                        PetsitterId = 46,
                        Text =
                            "Adipisci voluptatem at adipisci ad at optio ut non dolores. Consequatur et corporis placeat est saepe. Maiores reprehenderit soluta voluptates neque dignissimos eum asperiores rerum. Et quia ratione ea sint aliquam unde necessitatibus cum rerum.\n\nOmnis molestiae iste et. Iure impedit vero facilis dolore et nihil nam earum dolore. Eos voluptate vel veniam non. Qui sed aliquid aut qui maiores facere vero. Consequatur tenetur dolor quo aliquam ex sint qui asperiores veniam. Ut voluptate libero odio eligendi reiciendis aut ut doloremque.\n\nOfficia asperiores nulla. Ex necessitatibus necessitatibus itaque quisquam aut repellendus ipsam est. Rerum aut asperiores non earum tenetur illum repellat nihil. Quia provident voluptates velit voluptatum.\n\nEum nam recusandae commodi repellendus doloribus. Repellat doloremque error inventore error nobis. Explicabo voluptatem est consequatur officiis perferendis suscipit. Enim aliquam officia. Corrupti libero qui reiciendis deleniti laudantium maxime. A est quo iure aspernatur aut qui."
                    },
                    new
                    {
                        Id = 14,
                        ClientId = 28,
                        PetsitterId = 58,
                        Text =
                            "Iusto quod quibusdam vitae molestias modi animi animi sapiente. Quod aliquid soluta est. Quas quod dolor ab. Deserunt illum et.\n\nEnim ullam quo omnis et voluptate. Et quos sequi eum. Officia enim possimus debitis eos repellendus totam numquam. Aperiam laborum aut est voluptas. Eos nemo dolorem et cum consectetur quidem velit et.\n\nNon quod error et amet dolorum iure consequatur sequi. Nostrum quia minus aperiam mollitia reprehenderit qui ad est. Voluptatem deserunt expedita ipsam laborum quia ut sequi et. Fugit quo doloribus voluptatem aliquam qui est accusamus nulla asperiores. Et nobis necessitatibus similique aut iusto. Beatae et dolores et incidunt inventore nobis.\n\nMagnam illum eos. Ut nemo quia. Blanditiis eius impedit omnis accusamus quod ad molestiae eligendi. Aliquid et voluptas maxime excepturi. Tenetur architecto cumque blanditiis consectetur id non suscipit quia rerum. Ab maiores repudiandae aliquam quos deleniti."
                    },
                    new
                    {
                        Id = 15,
                        ClientId = 4,
                        PetsitterId = 35,
                        Text =
                            "Consequatur quia veritatis eius dolores ut porro suscipit. Voluptatem quas nemo. Consequuntur neque est facere natus pariatur quis quis blanditiis incidunt. Tempora dignissimos omnis vitae eos. Et harum et nesciunt ratione et. Labore optio et non alias nostrum voluptatem saepe.\n\nTemporibus explicabo rerum. In voluptatem mollitia ex ex reiciendis quisquam doloribus. Omnis quidem voluptatum. Eligendi officiis cum vel voluptatibus exercitationem ut. Et repellendus architecto consequatur neque voluptates dignissimos.\n\nDoloribus doloribus aut optio ab consequatur. Et autem necessitatibus. Dolore facilis corporis in non est et voluptatem et velit. Et sint numquam quo deleniti occaecati doloribus consectetur et.\n\nDolorum est est et et rerum molestias. Aut amet ea illo ut eius atque dolores. Rem minima nihil quam incidunt dolor amet inventore atque. Rerum sint vel animi qui."
                    });
            });

            modelBuilder.Entity("PetSupport.Core.Entities.Client", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .UseIdentityColumn();

                b.Property<string>("Email")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("PhoneNumber")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Surname")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Clients");

                b.HasData(
                    new
                    {
                        Id = 1,
                        Email = "Tabitha81@gmail.com",
                        Name = "Tabitha",
                        PhoneNumber = "(367) 863-7564 x5861",
                        Surname = "Marquardt"
                    },
                    new
                    {
                        Id = 2,
                        Email = "Clifton.Metz@yahoo.com",
                        Name = "Clifton",
                        PhoneNumber = "1-637-392-0725 x0811",
                        Surname = "Metz"
                    },
                    new
                    {
                        Id = 3,
                        Email = "Rosa58@yahoo.com",
                        Name = "Rosa",
                        PhoneNumber = "(205) 555-6609 x520",
                        Surname = "Braun"
                    },
                    new
                    {
                        Id = 4,
                        Email = "Salvatore.Luettgen41@hotmail.com",
                        Name = "Salvatore",
                        PhoneNumber = "833-734-8284 x85146",
                        Surname = "Luettgen"
                    },
                    new
                    {
                        Id = 5,
                        Email = "Dixie_Erdman98@hotmail.com",
                        Name = "Dixie",
                        PhoneNumber = "957-710-3185 x1359",
                        Surname = "Erdman"
                    },
                    new
                    {
                        Id = 6,
                        Email = "Calvin48@hotmail.com",
                        Name = "Calvin",
                        PhoneNumber = "970.985.5294 x882",
                        Surname = "Weber"
                    },
                    new
                    {
                        Id = 7,
                        Email = "June36@gmail.com",
                        Name = "June",
                        PhoneNumber = "338-637-6082 x77943",
                        Surname = "O'Keefe"
                    },
                    new
                    {
                        Id = 8,
                        Email = "Arlene_Rosenbaum82@yahoo.com",
                        Name = "Arlene",
                        PhoneNumber = "1-836-723-4030 x629",
                        Surname = "Rosenbaum"
                    },
                    new
                    {
                        Id = 9,
                        Email = "Lila.Murphy55@hotmail.com",
                        Name = "Lila",
                        PhoneNumber = "(575) 708-6262 x7984",
                        Surname = "Murphy"
                    },
                    new
                    {
                        Id = 10,
                        Email = "Sammy.Terry@gmail.com",
                        Name = "Sammy",
                        PhoneNumber = "451-711-4431 x68832",
                        Surname = "Terry"
                    },
                    new
                    {
                        Id = 11,
                        Email = "Felipe99@yahoo.com",
                        Name = "Felipe",
                        PhoneNumber = "1-443-765-5820",
                        Surname = "Bahringer"
                    },
                    new
                    {
                        Id = 12,
                        Email = "Tammy_Marquardt61@gmail.com",
                        Name = "Tammy",
                        PhoneNumber = "1-238-936-6451 x46634",
                        Surname = "Marquardt"
                    },
                    new
                    {
                        Id = 13,
                        Email = "Alfred.Murazik42@yahoo.com",
                        Name = "Alfred",
                        PhoneNumber = "(650) 663-3103",
                        Surname = "Murazik"
                    },
                    new
                    {
                        Id = 14,
                        Email = "Marcus_Hermiston@yahoo.com",
                        Name = "Marcus",
                        PhoneNumber = "1-368-503-9574 x1287",
                        Surname = "Hermiston"
                    },
                    new
                    {
                        Id = 15,
                        Email = "Nettie34@hotmail.com",
                        Name = "Nettie",
                        PhoneNumber = "(643) 801-8923",
                        Surname = "Will"
                    },
                    new
                    {
                        Id = 16,
                        Email = "Jesse_Bernier92@yahoo.com",
                        Name = "Jesse",
                        PhoneNumber = "413-632-5828 x16164",
                        Surname = "Bernier"
                    },
                    new
                    {
                        Id = 17,
                        Email = "Lucille_Veum20@gmail.com",
                        Name = "Lucille",
                        PhoneNumber = "1-664-385-3643",
                        Surname = "Veum"
                    },
                    new
                    {
                        Id = 18,
                        Email = "Muriel6@gmail.com",
                        Name = "Muriel",
                        PhoneNumber = "(909) 739-3988 x41259",
                        Surname = "Skiles"
                    },
                    new
                    {
                        Id = 19,
                        Email = "Thelma_VonRueden20@hotmail.com",
                        Name = "Thelma",
                        PhoneNumber = "228.838.8882 x1075",
                        Surname = "VonRueden"
                    },
                    new
                    {
                        Id = 20,
                        Email = "Dallas.Kuhic1@gmail.com",
                        Name = "Dallas",
                        PhoneNumber = "(614) 758-1162 x7491",
                        Surname = "Kuhic"
                    },
                    new
                    {
                        Id = 21,
                        Email = "Neal29@yahoo.com",
                        Name = "Neal",
                        PhoneNumber = "(419) 734-5333 x49286",
                        Surname = "Turner"
                    },
                    new
                    {
                        Id = 22,
                        Email = "Katherine_Cole61@yahoo.com",
                        Name = "Katherine",
                        PhoneNumber = "283.755.0135 x356",
                        Surname = "Cole"
                    },
                    new
                    {
                        Id = 23,
                        Email = "Patricia_Morar2@hotmail.com",
                        Name = "Patricia",
                        PhoneNumber = "(376) 631-4228",
                        Surname = "Morar"
                    },
                    new
                    {
                        Id = 24,
                        Email = "Mary_Crona@gmail.com",
                        Name = "Mary",
                        PhoneNumber = "(278) 458-0728 x2167",
                        Surname = "Crona"
                    },
                    new
                    {
                        Id = 25,
                        Email = "Chad78@hotmail.com",
                        Name = "Chad",
                        PhoneNumber = "787-410-9624 x667",
                        Surname = "Koss"
                    },
                    new
                    {
                        Id = 26,
                        Email = "Leah_Steuber@yahoo.com",
                        Name = "Leah",
                        PhoneNumber = "646.777.6076 x844",
                        Surname = "Steuber"
                    },
                    new
                    {
                        Id = 27,
                        Email = "Irene.Upton@yahoo.com",
                        Name = "Irene",
                        PhoneNumber = "(663) 715-6865 x8054",
                        Surname = "Upton"
                    },
                    new
                    {
                        Id = 28,
                        Email = "Tracy.Thompson@yahoo.com",
                        Name = "Tracy",
                        PhoneNumber = "1-282-558-9912 x302",
                        Surname = "Thompson"
                    },
                    new
                    {
                        Id = 29,
                        Email = "Jean58@yahoo.com",
                        Name = "Jean",
                        PhoneNumber = "667-907-0061 x783",
                        Surname = "Olson"
                    },
                    new
                    {
                        Id = 30,
                        Email = "Viola_Becker31@yahoo.com",
                        Name = "Viola",
                        PhoneNumber = "818.996.3457",
                        Surname = "Becker"
                    });
            });

            modelBuilder.Entity("PetSupport.Core.Entities.Petsitter", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .UseIdentityColumn();

                b.Property<string>("City")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Description")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Email")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Password")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("PhoneNumber")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("PhotoId")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Surname")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Petsitters");

                b.HasData(
                    new
                    {
                        Id = 31,
                        City = "West Ellen",
                        Description =
                            "Enim tempore et aut labore repellendus officia ut omnis voluptate beatae voluptas quam non animi dolor et repellendus id aut quisquam ullam officiis ad dolores dolor cumque aut ab et.",
                        Email = "Andrew_Bogan31@hotmail.com",
                        Name = "Andrew",
                        Password = "d2618bd1-40dc-4a88-91f4-e17a8cc157ed",
                        PhoneNumber = "910-546-9101 x100",
                        PhotoId = "https://picsum.photos/640/480/?image=1033",
                        Surname = "Bogan"
                    },
                    new
                    {
                        Id = 32,
                        City = "Isaiahbury",
                        Description =
                            "Quia sit sint qui eligendi officia ea et molestias delectus aut sint qui numquam maxime molestias nam eveniet numquam et omnis enim odit ea pariatur nam est quidem voluptas numquam.",
                        Email = "Maurice.Hane1@hotmail.com",
                        Name = "Maurice",
                        Password = "b3d90daf-0c36-44f4-b81f-ee0e21fdcae4",
                        PhoneNumber = "(980) 290-5085",
                        PhotoId = "https://picsum.photos/640/480/?image=135",
                        Surname = "Hane"
                    },
                    new
                    {
                        Id = 33,
                        City = "Cassandramouth",
                        Description =
                            "Unde est et laborum provident quos qui ipsum quas alias dolores voluptates nisi accusamus asperiores perferendis praesentium nisi qui eius sed et sed et harum assumenda amet et quasi tempore.",
                        Email = "Wilbur.Bartoletti@hotmail.com",
                        Name = "Wilbur",
                        Password = "4ac66540-6b93-4790-adc0-e03b11b0f9ac",
                        PhoneNumber = "695.206.2480",
                        PhotoId = "https://picsum.photos/640/480/?image=495",
                        Surname = "Bartoletti"
                    },
                    new
                    {
                        Id = 34,
                        City = "Quitzonbury",
                        Description =
                            "Nostrum tempora debitis sit ex consequatur itaque sunt optio veniam quia sed amet sint esse hic recusandae debitis explicabo quisquam corporis molestiae earum aperiam ex at quo et voluptatem mollitia.",
                        Email = "Tyrone.Hoppe86@yahoo.com",
                        Name = "Tyrone",
                        Password = "e6fe39b0-7de2-4b32-be47-80ec42656460",
                        PhoneNumber = "382.942.6858",
                        PhotoId = "https://picsum.photos/640/480/?image=75",
                        Surname = "Hoppe"
                    },
                    new
                    {
                        Id = 35,
                        City = "Dustinborough",
                        Description =
                            "Nam in quas explicabo nobis ea numquam in vel omnis ipsam porro qui deleniti eum non velit repudiandae dolor minus nam ex sed quas officia facere aspernatur velit quia dolorum.",
                        Email = "Cary52@gmail.com",
                        Name = "Cary",
                        Password = "c682f983-87a1-4cfa-b38a-276df1c9ea7f",
                        PhoneNumber = "1-949-667-7532 x86510",
                        PhotoId = "https://picsum.photos/640/480/?image=891",
                        Surname = "Bergstrom"
                    },
                    new
                    {
                        Id = 36,
                        City = "Mikelstad",
                        Description =
                            "Deleniti quae dicta perferendis cupiditate cupiditate saepe tempora nulla officia eius sit iure consequuntur temporibus et rerum accusamus illo recusandae aut dolores repudiandae in eius sapiente accusamus nostrum qui provident.",
                        Email = "Ora.Nienow74@hotmail.com",
                        Name = "Ora",
                        Password = "ba59d2ed-1854-470e-a7fc-f5eb41dd4f65",
                        PhoneNumber = "229-438-3195 x93817",
                        PhotoId = "https://picsum.photos/640/480/?image=921",
                        Surname = "Nienow"
                    },
                    new
                    {
                        Id = 37,
                        City = "West Sally",
                        Description =
                            "Libero maiores qui id aliquam qui laboriosam impedit rerum est iure sit aperiam praesentium laboriosam illum optio necessitatibus rerum aut omnis et molestiae enim excepturi dolor quia quae qui perferendis.",
                        Email = "Dominic.Stanton66@yahoo.com",
                        Name = "Dominic",
                        Password = "aff0cc1e-f062-4169-9d55-842723f7aa12",
                        PhoneNumber = "(299) 595-6915 x7566",
                        PhotoId = "https://picsum.photos/640/480/?image=945",
                        Surname = "Stanton"
                    },
                    new
                    {
                        Id = 38,
                        City = "Halieburgh",
                        Description =
                            "Eius maxime repellat in rem voluptatum itaque reprehenderit adipisci eos inventore velit nihil rerum illo et magnam et porro placeat velit non laboriosam nam sequi voluptas eos eligendi aliquid ut.",
                        Email = "Eva_Graham35@gmail.com",
                        Name = "Eva",
                        Password = "3702243c-6e22-4505-b4b5-9cebab3db2c1",
                        PhoneNumber = "837.681.8854",
                        PhotoId = "https://picsum.photos/640/480/?image=166",
                        Surname = "Graham"
                    },
                    new
                    {
                        Id = 39,
                        City = "North Carastad",
                        Description =
                            "Ut tempore ut rem hic beatae non est voluptas ullam ut quia et rem est quae consequatur inventore est at totam voluptatem et repellat nisi rem ad sunt veritatis et.",
                        Email = "Caroline_Beier@yahoo.com",
                        Name = "Caroline",
                        Password = "b10d398b-9a7d-4fc8-9222-ec8eed2d4df4",
                        PhoneNumber = "1-601-661-8104",
                        PhotoId = "https://picsum.photos/640/480/?image=687",
                        Surname = "Beier"
                    },
                    new
                    {
                        Id = 40,
                        City = "New Daniela",
                        Description =
                            "Illo dolor eaque non voluptatem molestiae similique aliquam dignissimos repellendus nobis voluptate voluptatem voluptates voluptatem aut voluptatum in fugit quidem rerum veritatis velit vero voluptatem eos nihil ad animi aut.",
                        Email = "Kerry.Ryan@gmail.com",
                        Name = "Kerry",
                        Password = "ec34fe9e-fe46-49ed-ab43-504aac0ca3df",
                        PhoneNumber = "1-987-971-1491 x48358",
                        PhotoId = "https://picsum.photos/640/480/?image=697",
                        Surname = "Ryan"
                    },
                    new
                    {
                        Id = 41,
                        City = "Colefort",
                        Description =
                            "Aut recusandae laudantium a voluptatem deleniti aperiam dolores ea nulla dolore iure praesentium voluptas enim aliquam asperiores occaecati optio rem qui perferendis quia et accusamus voluptatem eligendi facilis temporibus quidem.",
                        Email = "Kelly_Hettinger@hotmail.com",
                        Name = "Kelly",
                        Password = "ae16fdcb-f09a-4fa2-a637-46d257c864c6",
                        PhoneNumber = "744.990.8399 x12102",
                        PhotoId = "https://picsum.photos/640/480/?image=886",
                        Surname = "Hettinger"
                    },
                    new
                    {
                        Id = 42,
                        City = "Aubreyburgh",
                        Description =
                            "Maiores excepturi et dicta quo earum sed consequatur quod sequi perspiciatis et quas molestiae maiores eius et voluptas praesentium doloribus molestiae reiciendis aut a sed vitae facilis velit ab neque.",
                        Email = "Timmy_Grant95@gmail.com",
                        Name = "Timmy",
                        Password = "393da671-8524-4c8a-8596-6665bd064e1d",
                        PhoneNumber = "1-698-222-9107 x9077",
                        PhotoId = "https://picsum.photos/640/480/?image=636",
                        Surname = "Grant"
                    },
                    new
                    {
                        Id = 43,
                        City = "Laylatown",
                        Description =
                            "Quam quaerat laudantium corrupti occaecati et reprehenderit tempora et recusandae quia eveniet dolor ad corporis deleniti ad quae rerum nulla dolor totam impedit quo molestias dolorem velit autem quia in.",
                        Email = "Terrence.Krajcik17@yahoo.com",
                        Name = "Terrence",
                        Password = "0d48e17d-8c90-4949-a6f7-42c504a85f89",
                        PhoneNumber = "1-517-444-5503 x1862",
                        PhotoId = "https://picsum.photos/640/480/?image=949",
                        Surname = "Krajcik"
                    },
                    new
                    {
                        Id = 44,
                        City = "Brisatown",
                        Description =
                            "Aliquid enim amet mollitia minima quibusdam vero asperiores tenetur aspernatur sed corporis eos eum nihil nemo deleniti dolor architecto aut tempore vel omnis incidunt sint quis est illum id culpa.",
                        Email = "Priscilla_Wehner@hotmail.com",
                        Name = "Priscilla",
                        Password = "3783b361-f3bf-4f25-8008-fef72cd7d29a",
                        PhoneNumber = "1-205-711-9956 x96609",
                        PhotoId = "https://picsum.photos/640/480/?image=273",
                        Surname = "Wehner"
                    },
                    new
                    {
                        Id = 45,
                        City = "Pablomouth",
                        Description =
                            "Sint aut molestiae quae consequatur quam assumenda temporibus aut veritatis et et nemo voluptas quaerat cupiditate soluta et voluptatem animi officia accusantium atque est perferendis ea soluta aut et dolore.",
                        Email = "Mary.Jenkins60@yahoo.com",
                        Name = "Mary",
                        Password = "2f89ac0f-9571-460c-8dbe-f6b359117b3e",
                        PhoneNumber = "894-976-8559",
                        PhotoId = "https://picsum.photos/640/480/?image=477",
                        Surname = "Jenkins"
                    },
                    new
                    {
                        Id = 46,
                        City = "South Angus",
                        Description =
                            "Odit molestiae quia vel omnis consectetur tempora consequatur numquam impedit cupiditate autem quisquam sapiente praesentium facere adipisci voluptatibus illo beatae sint accusamus qui molestiae ab nobis sed odio dignissimos aut.",
                        Email = "Traci_McGlynn84@yahoo.com",
                        Name = "Traci",
                        Password = "1f69dea0-68cd-436c-8f28-1a75ba9e3842",
                        PhoneNumber = "(857) 840-4370 x47778",
                        PhotoId = "https://picsum.photos/640/480/?image=712",
                        Surname = "McGlynn"
                    },
                    new
                    {
                        Id = 47,
                        City = "New Deionfort",
                        Description =
                            "Reprehenderit sint nemo reiciendis non voluptatem porro ut unde iure magnam consequatur eveniet voluptas vero veritatis occaecati eligendi dolorem et est repellat id facere nisi vitae hic quis voluptatum laborum.",
                        Email = "Jeannie.OConnell@yahoo.com",
                        Name = "Jeannie",
                        Password = "b7e68e5e-cf70-4d05-826e-4959b4c09c81",
                        PhoneNumber = "1-548-589-2213 x80733",
                        PhotoId = "https://picsum.photos/640/480/?image=502",
                        Surname = "O'Connell"
                    },
                    new
                    {
                        Id = 48,
                        City = "Sarahside",
                        Description =
                            "Enim qui occaecati cum quia commodi adipisci eum nihil dolorem est non et minima quia occaecati aspernatur mollitia atque quo sint doloribus in facere hic mollitia accusamus facere quo quis.",
                        Email = "Agnes57@gmail.com",
                        Name = "Agnes",
                        Password = "e0247523-4d1f-43fd-9c62-00827f16113b",
                        PhoneNumber = "415-856-5375",
                        PhotoId = "https://picsum.photos/640/480/?image=338",
                        Surname = "Cronin"
                    },
                    new
                    {
                        Id = 49,
                        City = "West Alexandrine",
                        Description =
                            "Cupiditate aperiam sint non minus quasi beatae et quam molestiae non eos quo fuga quia tenetur sed dignissimos et neque quia quae ex explicabo ratione modi praesentium aspernatur soluta sit.",
                        Email = "Marty.Medhurst@gmail.com",
                        Name = "Marty",
                        Password = "90db37a1-c3d4-4b40-bf8e-6763462dfb98",
                        PhoneNumber = "1-806-658-3038 x776",
                        PhotoId = "https://picsum.photos/640/480/?image=865",
                        Surname = "Medhurst"
                    },
                    new
                    {
                        Id = 50,
                        City = "New Lorena",
                        Description =
                            "Quia voluptatem placeat et necessitatibus tempora iusto itaque cumque quis occaecati expedita doloremque repudiandae illum velit sapiente rerum voluptatem perspiciatis dolores et esse voluptatibus maiores recusandae ut voluptas quo pariatur.",
                        Email = "Hilda_Gibson77@gmail.com",
                        Name = "Hilda",
                        Password = "3738054f-d13b-4ab7-9b02-c8c89fede704",
                        PhoneNumber = "636.574.1464",
                        PhotoId = "https://picsum.photos/640/480/?image=898",
                        Surname = "Gibson"
                    },
                    new
                    {
                        Id = 51,
                        City = "North Tatyana",
                        Description =
                            "Accusamus praesentium fugit et sit corporis illum magni veritatis voluptatem blanditiis voluptas esse voluptatem debitis esse minima repudiandae debitis recusandae laboriosam iusto eaque ea provident et voluptatem consequatur quo a.",
                        Email = "Max_Reynolds43@yahoo.com",
                        Name = "Max",
                        Password = "7f84667d-7930-44a3-b85d-edf3445f45bb",
                        PhoneNumber = "(968) 424-9257 x70936",
                        PhotoId = "https://picsum.photos/640/480/?image=563",
                        Surname = "Reynolds"
                    },
                    new
                    {
                        Id = 52,
                        City = "New Koreyborough",
                        Description =
                            "Temporibus corporis blanditiis ut itaque nemo quae blanditiis qui animi qui laborum est quo atque natus esse praesentium perferendis est quasi et non eum aut est est est architecto et.",
                        Email = "Luther.Schimmel62@gmail.com",
                        Name = "Luther",
                        Password = "51c79a5d-0542-459e-a24a-3e94fd6eea6c",
                        PhoneNumber = "(765) 389-1447",
                        PhotoId = "https://picsum.photos/640/480/?image=635",
                        Surname = "Schimmel"
                    },
                    new
                    {
                        Id = 53,
                        City = "East Herbert",
                        Description =
                            "Voluptatem debitis reiciendis ea possimus voluptas nesciunt illo magni atque voluptatibus dolor alias et suscipit nisi aut laudantium ut asperiores molestias aspernatur consequatur sit eaque quae doloremque tempora aliquid corporis.",
                        Email = "Edgar.Russel@yahoo.com",
                        Name = "Edgar",
                        Password = "f3787945-9675-42b2-9e63-5ec96e6a5d20",
                        PhoneNumber = "(475) 375-5836",
                        PhotoId = "https://picsum.photos/640/480/?image=25",
                        Surname = "Russel"
                    },
                    new
                    {
                        Id = 54,
                        City = "Hattieton",
                        Description =
                            "Eligendi ducimus consectetur iusto voluptate iure non in voluptas earum eius iure perferendis quos nobis sed nemo et eos ipsa in et omnis vel debitis provident non ipsa sint sint.",
                        Email = "Kathryn70@gmail.com",
                        Name = "Kathryn",
                        Password = "8406f66a-4c40-4c9d-b610-ac273feccfc0",
                        PhoneNumber = "843-661-5618",
                        PhotoId = "https://picsum.photos/640/480/?image=618",
                        Surname = "Gutmann"
                    },
                    new
                    {
                        Id = 55,
                        City = "Morarville",
                        Description =
                            "Corrupti consequatur itaque natus saepe error omnis voluptas consequatur amet sit minima aperiam facere quia qui voluptas numquam et officiis optio fugit ducimus in asperiores aut velit et quos est.",
                        Email = "Sergio69@gmail.com",
                        Name = "Sergio",
                        Password = "78ea2fcc-bd8b-4707-950f-1c09c1915c9c",
                        PhoneNumber = "(339) 734-0186 x358",
                        PhotoId = "https://picsum.photos/640/480/?image=944",
                        Surname = "Adams"
                    },
                    new
                    {
                        Id = 56,
                        City = "Port Kenna",
                        Description =
                            "Tenetur commodi itaque est eum consequatur nisi fugiat atque dolores voluptate ipsa incidunt quia perferendis excepturi beatae doloribus labore rerum voluptas nihil eveniet in quidem aut esse nihil enim voluptas.",
                        Email = "Bryan.Barton43@hotmail.com",
                        Name = "Bryan",
                        Password = "b5f2ff29-6bee-4efa-94ca-ec9e932fb3b1",
                        PhoneNumber = "571.223.9353",
                        PhotoId = "https://picsum.photos/640/480/?image=947",
                        Surname = "Barton"
                    },
                    new
                    {
                        Id = 57,
                        City = "Lenoraborough",
                        Description =
                            "Laudantium cum nobis possimus hic quia incidunt placeat quasi doloribus quasi cupiditate est perferendis iste explicabo vitae fugiat in et nesciunt quo non cum labore velit nihil itaque amet esse.",
                        Email = "Jeremiah_Walter@hotmail.com",
                        Name = "Jeremiah",
                        Password = "330b78a4-6c8b-4483-8874-7a5bc5c21820",
                        PhoneNumber = "1-356-663-1545 x00565",
                        PhotoId = "https://picsum.photos/640/480/?image=515",
                        Surname = "Walter"
                    },
                    new
                    {
                        Id = 58,
                        City = "Cartwrighthaven",
                        Description =
                            "Nihil quia consectetur aliquid unde facere dignissimos nihil nostrum iusto porro illum voluptates ullam minima ipsam sit architecto pariatur quia non qui nihil odio corrupti alias doloremque nihil illum quidem.",
                        Email = "Alexandra71@hotmail.com",
                        Name = "Alexandra",
                        Password = "280bcb53-0bc8-4754-b9e5-025d237af3af",
                        PhoneNumber = "988-749-4740 x57825",
                        PhotoId = "https://picsum.photos/640/480/?image=623",
                        Surname = "Schoen"
                    },
                    new
                    {
                        Id = 59,
                        City = "East Rodgerhaven",
                        Description =
                            "Veniam dolorem rerum fuga nesciunt occaecati culpa ut quaerat sint ea et nihil eos eos deleniti tenetur non totam facilis voluptatem ullam atque quos natus placeat mollitia quaerat dolor aut.",
                        Email = "Clifford.Schamberger@gmail.com",
                        Name = "Clifford",
                        Password = "5fc4b9f9-8368-4885-aa3d-356089dc271e",
                        PhoneNumber = "1-446-408-5067 x8570",
                        PhotoId = "https://picsum.photos/640/480/?image=147",
                        Surname = "Schamberger"
                    },
                    new
                    {
                        Id = 60,
                        City = "Lake Alan",
                        Description =
                            "Qui et quia recusandae eaque iste vero vel illo eos cum aut voluptatibus et veritatis quam et deserunt quia voluptatem magni placeat et hic dicta consectetur natus dignissimos sed voluptatibus.",
                        Email = "Margie33@gmail.com",
                        Name = "Margie",
                        Password = "0d26f979-20db-4435-8cb5-930b8ec0aba9",
                        PhoneNumber = "1-648-672-9310 x493",
                        PhotoId = "https://picsum.photos/640/480/?image=392",
                        Surname = "Grant"
                    });
            });

            modelBuilder.Entity("PetSupport.Core.Entities.PetsitterService", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .UseIdentityColumn();

                b.Property<int>("PetsitterId")
                    .HasColumnType("int");

                b.Property<double>("Price")
                    .HasColumnType("float");

                b.Property<int>("ServiceId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("PetsitterId");

                b.HasIndex("ServiceId");

                b.ToTable("PetSupportServices");

                b.HasData(
                    new
                    {
                        Id = 1,
                        PetsitterId = 51,
                        Price = 813.63999999999999,
                        ServiceId = 3
                    },
                    new
                    {
                        Id = 2,
                        PetsitterId = 53,
                        Price = 726.10000000000002,
                        ServiceId = 21
                    },
                    new
                    {
                        Id = 3,
                        PetsitterId = 45,
                        Price = 340.91000000000003,
                        ServiceId = 26
                    },
                    new
                    {
                        Id = 4,
                        PetsitterId = 52,
                        Price = 791.52999999999997,
                        ServiceId = 29
                    },
                    new
                    {
                        Id = 5,
                        PetsitterId = 40,
                        Price = 164.88999999999999,
                        ServiceId = 23
                    },
                    new
                    {
                        Id = 6,
                        PetsitterId = 52,
                        Price = 887.14999999999998,
                        ServiceId = 17
                    },
                    new
                    {
                        Id = 7,
                        PetsitterId = 32,
                        Price = 210.86000000000001,
                        ServiceId = 1
                    },
                    new
                    {
                        Id = 8,
                        PetsitterId = 33,
                        Price = 224.19,
                        ServiceId = 26
                    },
                    new
                    {
                        Id = 9,
                        PetsitterId = 56,
                        Price = 994.41999999999996,
                        ServiceId = 26
                    },
                    new
                    {
                        Id = 10,
                        PetsitterId = 43,
                        Price = 76.560000000000002,
                        ServiceId = 9
                    },
                    new
                    {
                        Id = 11,
                        PetsitterId = 45,
                        Price = 269.37,
                        ServiceId = 12
                    },
                    new
                    {
                        Id = 12,
                        PetsitterId = 59,
                        Price = 979.75999999999999,
                        ServiceId = 28
                    },
                    new
                    {
                        Id = 13,
                        PetsitterId = 49,
                        Price = 905.73000000000002,
                        ServiceId = 15
                    },
                    new
                    {
                        Id = 14,
                        PetsitterId = 45,
                        Price = 288.44999999999999,
                        ServiceId = 16
                    },
                    new
                    {
                        Id = 15,
                        PetsitterId = 43,
                        Price = 989.89999999999998,
                        ServiceId = 11
                    },
                    new
                    {
                        Id = 16,
                        PetsitterId = 39,
                        Price = 803.47000000000003,
                        ServiceId = 27
                    },
                    new
                    {
                        Id = 17,
                        PetsitterId = 39,
                        Price = 438.85000000000002,
                        ServiceId = 25
                    },
                    new
                    {
                        Id = 18,
                        PetsitterId = 45,
                        Price = 811.55999999999995,
                        ServiceId = 7
                    },
                    new
                    {
                        Id = 19,
                        PetsitterId = 55,
                        Price = 227.38999999999999,
                        ServiceId = 19
                    },
                    new
                    {
                        Id = 20,
                        PetsitterId = 48,
                        Price = 839.27999999999997,
                        ServiceId = 28
                    },
                    new
                    {
                        Id = 21,
                        PetsitterId = 52,
                        Price = 564.20000000000005,
                        ServiceId = 3
                    },
                    new
                    {
                        Id = 22,
                        PetsitterId = 38,
                        Price = 563.90999999999997,
                        ServiceId = 7
                    },
                    new
                    {
                        Id = 23,
                        PetsitterId = 46,
                        Price = 830.02999999999997,
                        ServiceId = 11
                    },
                    new
                    {
                        Id = 24,
                        PetsitterId = 36,
                        Price = 47.659999999999997,
                        ServiceId = 4
                    },
                    new
                    {
                        Id = 25,
                        PetsitterId = 60,
                        Price = 502.31999999999999,
                        ServiceId = 17
                    },
                    new
                    {
                        Id = 26,
                        PetsitterId = 58,
                        Price = 503.23000000000002,
                        ServiceId = 20
                    },
                    new
                    {
                        Id = 27,
                        PetsitterId = 38,
                        Price = 982.26999999999998,
                        ServiceId = 17
                    },
                    new
                    {
                        Id = 28,
                        PetsitterId = 36,
                        Price = 454.39999999999998,
                        ServiceId = 5
                    },
                    new
                    {
                        Id = 29,
                        PetsitterId = 50,
                        Price = 166.5,
                        ServiceId = 1
                    },
                    new
                    {
                        Id = 30,
                        PetsitterId = 44,
                        Price = 300.56,
                        ServiceId = 5
                    },
                    new
                    {
                        Id = 31,
                        PetsitterId = 53,
                        Price = 594.88999999999999,
                        ServiceId = 1
                    },
                    new
                    {
                        Id = 32,
                        PetsitterId = 32,
                        Price = 437.19999999999999,
                        ServiceId = 23
                    },
                    new
                    {
                        Id = 33,
                        PetsitterId = 52,
                        Price = 137.93000000000001,
                        ServiceId = 5
                    },
                    new
                    {
                        Id = 34,
                        PetsitterId = 43,
                        Price = 504.41000000000003,
                        ServiceId = 24
                    },
                    new
                    {
                        Id = 35,
                        PetsitterId = 60,
                        Price = 719.79999999999995,
                        ServiceId = 3
                    },
                    new
                    {
                        Id = 36,
                        PetsitterId = 42,
                        Price = 667.32000000000005,
                        ServiceId = 15
                    },
                    new
                    {
                        Id = 37,
                        PetsitterId = 40,
                        Price = 966.26999999999998,
                        ServiceId = 27
                    },
                    new
                    {
                        Id = 38,
                        PetsitterId = 52,
                        Price = 351.50999999999999,
                        ServiceId = 11
                    },
                    new
                    {
                        Id = 39,
                        PetsitterId = 56,
                        Price = 950.88999999999999,
                        ServiceId = 17
                    },
                    new
                    {
                        Id = 40,
                        PetsitterId = 34,
                        Price = 190.97999999999999,
                        ServiceId = 19
                    },
                    new
                    {
                        Id = 41,
                        PetsitterId = 42,
                        Price = 214.91,
                        ServiceId = 2
                    },
                    new
                    {
                        Id = 42,
                        PetsitterId = 46,
                        Price = 86.900000000000006,
                        ServiceId = 13
                    },
                    new
                    {
                        Id = 43,
                        PetsitterId = 44,
                        Price = 817.63999999999999,
                        ServiceId = 28
                    },
                    new
                    {
                        Id = 44,
                        PetsitterId = 32,
                        Price = 516.23000000000002,
                        ServiceId = 6
                    },
                    new
                    {
                        Id = 45,
                        PetsitterId = 41,
                        Price = 776.02999999999997,
                        ServiceId = 25
                    },
                    new
                    {
                        Id = 46,
                        PetsitterId = 45,
                        Price = 40.170000000000002,
                        ServiceId = 7
                    },
                    new
                    {
                        Id = 47,
                        PetsitterId = 53,
                        Price = 531.07000000000005,
                        ServiceId = 8
                    },
                    new
                    {
                        Id = 48,
                        PetsitterId = 45,
                        Price = 260.45999999999998,
                        ServiceId = 5
                    },
                    new
                    {
                        Id = 49,
                        PetsitterId = 41,
                        Price = 661.83000000000004,
                        ServiceId = 1
                    },
                    new
                    {
                        Id = 50,
                        PetsitterId = 38,
                        Price = 208.34,
                        ServiceId = 7
                    },
                    new
                    {
                        Id = 51,
                        PetsitterId = 45,
                        Price = 518.97000000000003,
                        ServiceId = 19
                    },
                    new
                    {
                        Id = 52,
                        PetsitterId = 59,
                        Price = 708.73000000000002,
                        ServiceId = 1
                    },
                    new
                    {
                        Id = 53,
                        PetsitterId = 39,
                        Price = 664.25999999999999,
                        ServiceId = 14
                    },
                    new
                    {
                        Id = 54,
                        PetsitterId = 50,
                        Price = 579.25999999999999,
                        ServiceId = 29
                    },
                    new
                    {
                        Id = 55,
                        PetsitterId = 56,
                        Price = 690.90999999999997,
                        ServiceId = 8
                    },
                    new
                    {
                        Id = 56,
                        PetsitterId = 44,
                        Price = 549.86000000000001,
                        ServiceId = 11
                    },
                    new
                    {
                        Id = 57,
                        PetsitterId = 48,
                        Price = 323.23000000000002,
                        ServiceId = 12
                    },
                    new
                    {
                        Id = 58,
                        PetsitterId = 58,
                        Price = 382.12,
                        ServiceId = 12
                    },
                    new
                    {
                        Id = 59,
                        PetsitterId = 50,
                        Price = 917.76999999999998,
                        ServiceId = 27
                    },
                    new
                    {
                        Id = 60,
                        PetsitterId = 59,
                        Price = 402.51999999999998,
                        ServiceId = 6
                    },
                    new
                    {
                        Id = 61,
                        PetsitterId = 43,
                        Price = 705.52999999999997,
                        ServiceId = 7
                    },
                    new
                    {
                        Id = 62,
                        PetsitterId = 49,
                        Price = 584.71000000000004,
                        ServiceId = 18
                    },
                    new
                    {
                        Id = 63,
                        PetsitterId = 60,
                        Price = 778.74000000000001,
                        ServiceId = 13
                    },
                    new
                    {
                        Id = 64,
                        PetsitterId = 33,
                        Price = 774.52999999999997,
                        ServiceId = 6
                    },
                    new
                    {
                        Id = 65,
                        PetsitterId = 42,
                        Price = 307.10000000000002,
                        ServiceId = 4
                    },
                    new
                    {
                        Id = 66,
                        PetsitterId = 59,
                        Price = 903.45000000000005,
                        ServiceId = 20
                    },
                    new
                    {
                        Id = 67,
                        PetsitterId = 48,
                        Price = 671.38,
                        ServiceId = 27
                    },
                    new
                    {
                        Id = 68,
                        PetsitterId = 34,
                        Price = 831.27999999999997,
                        ServiceId = 21
                    },
                    new
                    {
                        Id = 69,
                        PetsitterId = 57,
                        Price = 239.24000000000001,
                        ServiceId = 18
                    },
                    new
                    {
                        Id = 70,
                        PetsitterId = 35,
                        Price = 130.33000000000001,
                        ServiceId = 9
                    },
                    new
                    {
                        Id = 71,
                        PetsitterId = 54,
                        Price = 247.80000000000001,
                        ServiceId = 11
                    },
                    new
                    {
                        Id = 72,
                        PetsitterId = 38,
                        Price = 731.02999999999997,
                        ServiceId = 7
                    },
                    new
                    {
                        Id = 73,
                        PetsitterId = 57,
                        Price = 665.30999999999995,
                        ServiceId = 8
                    },
                    new
                    {
                        Id = 74,
                        PetsitterId = 34,
                        Price = 939.49000000000001,
                        ServiceId = 14
                    },
                    new
                    {
                        Id = 75,
                        PetsitterId = 54,
                        Price = 190.80000000000001,
                        ServiceId = 16
                    },
                    new
                    {
                        Id = 76,
                        PetsitterId = 47,
                        Price = 275.5,
                        ServiceId = 17
                    },
                    new
                    {
                        Id = 77,
                        PetsitterId = 33,
                        Price = 250.74000000000001,
                        ServiceId = 22
                    },
                    new
                    {
                        Id = 78,
                        PetsitterId = 31,
                        Price = 313.94,
                        ServiceId = 12
                    },
                    new
                    {
                        Id = 79,
                        PetsitterId = 52,
                        Price = 540.48000000000002,
                        ServiceId = 10
                    },
                    new
                    {
                        Id = 80,
                        PetsitterId = 57,
                        Price = 6.2199999999999998,
                        ServiceId = 22
                    },
                    new
                    {
                        Id = 81,
                        PetsitterId = 41,
                        Price = 132.31999999999999,
                        ServiceId = 26
                    },
                    new
                    {
                        Id = 82,
                        PetsitterId = 50,
                        Price = 853.30999999999995,
                        ServiceId = 9
                    },
                    new
                    {
                        Id = 83,
                        PetsitterId = 46,
                        Price = 891.88,
                        ServiceId = 4
                    },
                    new
                    {
                        Id = 84,
                        PetsitterId = 48,
                        Price = 410.12,
                        ServiceId = 3
                    },
                    new
                    {
                        Id = 85,
                        PetsitterId = 38,
                        Price = 430.45999999999998,
                        ServiceId = 14
                    },
                    new
                    {
                        Id = 86,
                        PetsitterId = 52,
                        Price = 161.72,
                        ServiceId = 11
                    },
                    new
                    {
                        Id = 87,
                        PetsitterId = 50,
                        Price = 38.770000000000003,
                        ServiceId = 11
                    },
                    new
                    {
                        Id = 88,
                        PetsitterId = 59,
                        Price = 579.94000000000005,
                        ServiceId = 2
                    },
                    new
                    {
                        Id = 89,
                        PetsitterId = 57,
                        Price = 950.14999999999998,
                        ServiceId = 24
                    },
                    new
                    {
                        Id = 90,
                        PetsitterId = 59,
                        Price = 896.72000000000003,
                        ServiceId = 16
                    });
            });

            modelBuilder.Entity("PetSupport.Core.Entities.Service", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .UseIdentityColumn();

                b.Property<string>("Description")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("ImageId")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Name")
                    .HasColumnType("int");

                b.Property<int>("Unit")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.ToTable("Services");

                b.HasData(
                    new
                    {
                        Id = 1,
                        Description = "Inventore animi aut consequatur pariatur.",
                        ImageId = "https://loremflickr.com/320/240?lock=1593273893",
                        Name = 3,
                        Unit = 1
                    },
                    new
                    {
                        Id = 2,
                        Description = "Velit soluta ut vero voluptatum.",
                        ImageId = "https://loremflickr.com/320/240?lock=699112102",
                        Name = 0,
                        Unit = 1
                    },
                    new
                    {
                        Id = 3,
                        Description = "In aut accusantium inventore ad.",
                        ImageId = "https://loremflickr.com/320/240?lock=783108421",
                        Name = 0,
                        Unit = 2
                    },
                    new
                    {
                        Id = 4,
                        Description = "Soluta incidunt cum exercitationem amet.",
                        ImageId = "https://loremflickr.com/320/240?lock=1632747932",
                        Name = 3,
                        Unit = 0
                    },
                    new
                    {
                        Id = 5,
                        Description = "Aut et inventore ex aut.",
                        ImageId = "https://loremflickr.com/320/240?lock=20025034",
                        Name = 4,
                        Unit = 2
                    },
                    new
                    {
                        Id = 6,
                        Description = "Voluptas quia saepe earum est.",
                        ImageId = "https://loremflickr.com/320/240?lock=1733792009",
                        Name = 0,
                        Unit = 0
                    },
                    new
                    {
                        Id = 7,
                        Description = "Est alias quia ut nulla.",
                        ImageId = "https://loremflickr.com/320/240?lock=1387034100",
                        Name = 1,
                        Unit = 0
                    },
                    new
                    {
                        Id = 8,
                        Description = "Voluptatum ut quos doloribus debitis.",
                        ImageId = "https://loremflickr.com/320/240?lock=294141962",
                        Name = 0,
                        Unit = 2
                    },
                    new
                    {
                        Id = 9,
                        Description = "Delectus modi dolorem ratione dignissimos.",
                        ImageId = "https://loremflickr.com/320/240?lock=395229782",
                        Name = 3,
                        Unit = 0
                    },
                    new
                    {
                        Id = 10,
                        Description = "Porro quod quas totam alias.",
                        ImageId = "https://loremflickr.com/320/240?lock=1797499681",
                        Name = 1,
                        Unit = 0
                    },
                    new
                    {
                        Id = 11,
                        Description = "Dolores omnis inventore et et.",
                        ImageId = "https://loremflickr.com/320/240?lock=2109180396",
                        Name = 2,
                        Unit = 0
                    },
                    new
                    {
                        Id = 12,
                        Description = "Cumque pariatur dignissimos tenetur enim.",
                        ImageId = "https://loremflickr.com/320/240?lock=1957442382",
                        Name = 0,
                        Unit = 1
                    },
                    new
                    {
                        Id = 13,
                        Description = "Fugit laudantium natus aspernatur natus.",
                        ImageId = "https://loremflickr.com/320/240?lock=1522666881",
                        Name = 3,
                        Unit = 0
                    },
                    new
                    {
                        Id = 14,
                        Description = "Unde consequatur ut non accusantium.",
                        ImageId = "https://loremflickr.com/320/240?lock=1996233359",
                        Name = 4,
                        Unit = 1
                    },
                    new
                    {
                        Id = 15,
                        Description = "Qui aspernatur mollitia accusantium quia.",
                        ImageId = "https://loremflickr.com/320/240?lock=641503537",
                        Name = 2,
                        Unit = 0
                    },
                    new
                    {
                        Id = 16,
                        Description = "Necessitatibus omnis molestiae eaque ab.",
                        ImageId = "https://loremflickr.com/320/240?lock=992154566",
                        Name = 4,
                        Unit = 2
                    },
                    new
                    {
                        Id = 17,
                        Description = "Reiciendis qui eius necessitatibus consequatur.",
                        ImageId = "https://loremflickr.com/320/240?lock=1717711096",
                        Name = 4,
                        Unit = 1
                    },
                    new
                    {
                        Id = 18,
                        Description = "Dolore corrupti qui itaque omnis.",
                        ImageId = "https://loremflickr.com/320/240?lock=848024654",
                        Name = 0,
                        Unit = 0
                    },
                    new
                    {
                        Id = 19,
                        Description = "Dicta dicta eos quaerat accusantium.",
                        ImageId = "https://loremflickr.com/320/240?lock=16952326",
                        Name = 1,
                        Unit = 1
                    },
                    new
                    {
                        Id = 20,
                        Description = "Et molestias tenetur tempora laborum.",
                        ImageId = "https://loremflickr.com/320/240?lock=708858163",
                        Name = 1,
                        Unit = 0
                    },
                    new
                    {
                        Id = 21,
                        Description = "Voluptatem voluptas explicabo reiciendis illum.",
                        ImageId = "https://loremflickr.com/320/240?lock=433432689",
                        Name = 3,
                        Unit = 0
                    },
                    new
                    {
                        Id = 22,
                        Description = "Consequatur tenetur quia aliquam illo.",
                        ImageId = "https://loremflickr.com/320/240?lock=1251311857",
                        Name = 2,
                        Unit = 1
                    },
                    new
                    {
                        Id = 23,
                        Description = "Assumenda quisquam quis et unde.",
                        ImageId = "https://loremflickr.com/320/240?lock=1553377512",
                        Name = 3,
                        Unit = 0
                    },
                    new
                    {
                        Id = 24,
                        Description = "Sit voluptatem debitis est nisi.",
                        ImageId = "https://loremflickr.com/320/240?lock=679990157",
                        Name = 3,
                        Unit = 0
                    },
                    new
                    {
                        Id = 25,
                        Description = "Dolores odit enim sunt sunt.",
                        ImageId = "https://loremflickr.com/320/240?lock=1541424634",
                        Name = 4,
                        Unit = 0
                    },
                    new
                    {
                        Id = 26,
                        Description = "Ipsa et blanditiis officia omnis.",
                        ImageId = "https://loremflickr.com/320/240?lock=963023015",
                        Name = 0,
                        Unit = 0
                    },
                    new
                    {
                        Id = 27,
                        Description = "Consequatur quidem exercitationem illo laborum.",
                        ImageId = "https://loremflickr.com/320/240?lock=631340919",
                        Name = 3,
                        Unit = 0
                    },
                    new
                    {
                        Id = 28,
                        Description = "Id ea est beatae illum.",
                        ImageId = "https://loremflickr.com/320/240?lock=1379883833",
                        Name = 4,
                        Unit = 1
                    },
                    new
                    {
                        Id = 29,
                        Description = "Dolores soluta et quia non.",
                        ImageId = "https://loremflickr.com/320/240?lock=516374598",
                        Name = 2,
                        Unit = 0
                    },
                    new
                    {
                        Id = 30,
                        Description = "Enim deserunt et dolor ut.",
                        ImageId = "https://loremflickr.com/320/240?lock=1096849045",
                        Name = 2,
                        Unit = 1
                    });
            });

            modelBuilder.Entity("PetSupport.Core.Entities.BookingMessage", b =>
            {
                b.HasOne("PetSupport.Core.Entities.Client", "Client")
                    .WithMany()
                    .HasForeignKey("ClientId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("PetSupport.Core.Entities.Petsitter", "Petsitter")
                    .WithMany()
                    .HasForeignKey("PetsitterId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Client");

                b.Navigation("Petsitter");
            });

            modelBuilder.Entity("PetSupport.Core.Entities.PetsitterService", b =>
            {
                b.HasOne("PetSupport.Core.Entities.Petsitter", "Petsitter")
                    .WithMany("Services")
                    .HasForeignKey("PetsitterId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("PetSupport.Core.Entities.Service", "Service")
                    .WithMany()
                    .HasForeignKey("ServiceId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Petsitter");

                b.Navigation("Service");
            });

            modelBuilder.Entity("PetSupport.Core.Entities.Petsitter", b => { b.Navigation("Services"); });
#pragma warning restore 612, 618
        }
    }
}