// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetSupport.Infrastructure.Data.Data;

namespace Petsupport.API2.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210116201330_UpdateEntities")]
    partial class UpdateEntities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("PetSupport.Core.Entities.BookingMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("PetsitterId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("PetsitterId");

                    b.ToTable("BookingMessages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 24,
                            PetsitterId = 57,
                            Text = "Labore dolor enim eveniet alias voluptate rerum. Inventore sit culpa est temporibus. Quidem optio et ut. Eveniet non voluptatum quo unde maxime atque.\n\nDelectus enim alias voluptatibus. Et nesciunt sint quos voluptates alias ab quis aut. Accusamus omnis ut assumenda qui maiores sed quos ut.\n\nSit voluptas laudantium voluptas voluptatem occaecati. Rerum veniam maxime dolor mollitia minus. Ipsa quisquam sed sequi ut perspiciatis est aspernatur optio nulla.\n\nQuo error quaerat et qui expedita repellendus qui in. Qui qui omnis deleniti et est. Aperiam est dolorem ut necessitatibus voluptate voluptatem sit suscipit. Et vel incidunt quasi dolorum reiciendis quis aut fugiat. Pariatur molestiae cupiditate consequatur minima corporis. Ut voluptatum qui inventore saepe a enim distinctio."
                        },
                        new
                        {
                            Id = 2,
                            ClientId = 19,
                            PetsitterId = 35,
                            Text = "Sequi repellat aut corrupti at dolores rerum nisi voluptas. Placeat reprehenderit tempore qui enim voluptatibus aut dolorem ex. Qui omnis asperiores at itaque placeat omnis vero sapiente voluptate. Ea dolorem voluptatibus cum vel maxime. Tempore tempore rerum sapiente voluptatem iusto.\n\nIure quasi est. Omnis doloribus voluptatem officia labore. Alias magnam unde aut autem dolor. Sint quis reprehenderit error eligendi ratione. Ut tempore dolores nobis enim fuga odio natus consequuntur itaque.\n\nIpsum tempore vero voluptatum explicabo ut quod veniam. Dolores necessitatibus similique exercitationem eos in. Et suscipit odio optio et quibusdam. Debitis quos culpa.\n\nTenetur dignissimos quia laborum quod est laborum. Veritatis saepe exercitationem voluptas hic et excepturi id. Non iure qui quae eaque dolores temporibus et nam. Quis et reiciendis maiores excepturi a quia voluptas recusandae."
                        },
                        new
                        {
                            Id = 3,
                            ClientId = 9,
                            PetsitterId = 42,
                            Text = "Dolore et nisi ipsum eaque aut maxime. Veniam voluptatem explicabo. Adipisci dolorem similique sint rerum suscipit fugit. Et labore aspernatur. Voluptates repellendus quis. Sed in commodi excepturi odit omnis sed sit optio.\n\nIure et impedit sunt exercitationem rerum quam voluptatem magni. Voluptate doloribus eaque neque placeat est consequatur. Quaerat quaerat aliquam quod et occaecati nihil tenetur qui. Esse dolorum iure modi dolorum qui.\n\nNumquam voluptatem et velit. Laudantium labore enim magni officia voluptas. Ex dicta velit esse iusto. Dolores est alias. Eum nisi corporis delectus.\n\nIpsum amet consequatur blanditiis iusto deserunt voluptatum. Delectus inventore est temporibus et est reprehenderit sed fuga. Aut sit nihil ut. Iste sunt beatae sequi doloremque assumenda blanditiis eveniet cupiditate. Minus aut earum eius officiis repudiandae voluptas. Nisi qui vel exercitationem nihil ratione aliquid."
                        },
                        new
                        {
                            Id = 4,
                            ClientId = 8,
                            PetsitterId = 54,
                            Text = "Et sunt dicta. In vel commodi ex. Ducimus dicta excepturi neque dolore tempora. Unde ducimus ut facere voluptatem suscipit porro beatae sint. Voluptatem eum non et labore quas.\n\nDistinctio asperiores est ut perspiciatis ea molestias natus voluptas. Quaerat itaque numquam quae. Vel aut nisi commodi delectus placeat. At consequatur nobis asperiores omnis voluptatibus molestiae. Non culpa est suscipit officia incidunt quia facilis.\n\nDolore omnis aut omnis qui in. Numquam et unde repellat. Qui est beatae dolores eos rerum eius omnis at non. Est a soluta dolorem. Praesentium dolore quaerat nesciunt iusto accusamus quisquam doloribus sint corporis. Odit et suscipit beatae.\n\nIpsam odio repellat quaerat qui explicabo deleniti molestiae. Facilis porro et quia mollitia. Velit enim possimus expedita. Quo praesentium ad illo dicta. Quo blanditiis fugit placeat sint qui aliquam. Rerum et ipsum."
                        },
                        new
                        {
                            Id = 5,
                            ClientId = 1,
                            PetsitterId = 49,
                            Text = "Minus vitae modi alias commodi adipisci impedit ipsa optio. Culpa quam qui et vero neque. Ipsum quo quaerat voluptatem ipsam id magni ut quis ad.\n\nLabore est facere et excepturi aut autem ab illo est. Consequuntur velit quam voluptatem itaque doloremque. Dolore repellendus beatae tempora qui dolorem eveniet possimus. Deleniti explicabo minus doloribus et possimus. Blanditiis et dolorem sint. Optio deleniti fugit.\n\nVelit magni est eveniet nisi adipisci. Cumque accusantium dolorem qui. Ut qui id. Nobis eveniet tenetur voluptatem minus quas quis ut sapiente. Aut aut animi unde corporis sapiente. Consequatur facere assumenda voluptatem occaecati.\n\nDolores nostrum saepe officia quia dignissimos similique labore ipsam voluptatem. Qui nesciunt similique. Voluptates possimus laboriosam recusandae aut vitae magni aspernatur."
                        },
                        new
                        {
                            Id = 6,
                            ClientId = 26,
                            PetsitterId = 45,
                            Text = "Tempora eum quo id neque possimus illo dolorem. Est repellendus rerum occaecati saepe accusamus. Minima sed quisquam aut est exercitationem voluptas aut consequatur. Aliquam illum commodi adipisci velit est laudantium. Laboriosam velit voluptatum porro pariatur dolorem aut quod ad. Aut qui velit doloribus non.\n\nRerum qui illo ut recusandae maiores eum autem in. Ut laudantium dolore adipisci inventore deleniti facere. Praesentium ipsam error nobis saepe cumque aperiam. Ut aperiam esse.\n\nId doloremque quis totam qui. Accusamus ea nihil est et enim. Et minima accusantium odit sint.\n\nIusto placeat sit aliquam quaerat dolore aliquid et. Ducimus autem vel in labore et et officiis qui rem. Rerum voluptatem eaque. Rerum esse sunt fugiat facere asperiores iusto sed. Occaecati dolorem at aut sed quia. Inventore alias quos aut vero."
                        },
                        new
                        {
                            Id = 7,
                            ClientId = 27,
                            PetsitterId = 47,
                            Text = "Nulla voluptatem autem dignissimos. Omnis quis quo aliquid laborum nulla tempore occaecati fugit. Aut tempore debitis aut velit omnis nihil possimus cupiditate magni.\n\nExpedita veritatis consequatur aspernatur ut quos mollitia voluptates voluptas inventore. Et quod ut qui expedita quas ea libero. Necessitatibus sunt delectus sit nam asperiores libero.\n\nQui at ipsam quo saepe et. Perspiciatis excepturi corporis dolor et sed beatae tenetur. Tempora eos officiis. Voluptas aliquam neque laudantium totam asperiores dicta aspernatur.\n\nUnde dolorem eos corrupti ducimus quia. Illum pariatur voluptates quos fugit. Illo corrupti dolorum nobis dolores aut sit iusto at autem. Expedita qui est pariatur consequatur ut ut omnis sint. Possimus aliquid dolor."
                        },
                        new
                        {
                            Id = 8,
                            ClientId = 19,
                            PetsitterId = 52,
                            Text = "Velit quis sapiente eos est voluptatem odit reiciendis. Nemo deserunt sunt dignissimos repellat eligendi aperiam nemo eum. Sint excepturi ducimus hic consequatur. Velit voluptates ullam eos quo delectus et voluptatem ut accusantium. Eum est consequatur debitis qui officiis occaecati.\n\nLaudantium rem beatae veritatis voluptatem voluptatum rerum voluptas ut magni. Laboriosam deserunt velit qui aliquid consequatur voluptas aut laboriosam qui. Ut aut consequuntur sed et dolorem molestiae non rerum. Ea quam deleniti est fugiat ut illum commodi vitae sed. Velit veritatis tempora.\n\nOmnis cupiditate est doloremque molestias magnam. Quidem sunt odit itaque. Vero inventore ut.\n\nAperiam voluptatibus quia porro est occaecati. Voluptatem est quaerat consectetur quibusdam corrupti voluptates. Sapiente consequuntur enim ut sequi est quam odit velit nulla. Est ullam optio quas."
                        },
                        new
                        {
                            Id = 9,
                            ClientId = 20,
                            PetsitterId = 31,
                            Text = "Doloremque dolore et omnis dolorem consequatur sed aut vero doloribus. Quo vitae velit. Sequi minus temporibus. Ratione aut laborum officiis aut officiis in autem ad quia. Ut omnis architecto error.\n\nEveniet ut dignissimos saepe tenetur animi natus fugit. Aut et non quaerat. Est ut rerum culpa ipsa quam quis. Et magnam non. Nobis porro possimus voluptatum omnis sint voluptatem eum aliquam eum. Odit consectetur veniam ab possimus.\n\nMolestias ut sit dolor consequatur alias repudiandae quos cupiditate. Veniam aut dignissimos adipisci soluta doloremque. Nulla ea optio dolore omnis quia debitis quis reprehenderit necessitatibus. Iure possimus consequatur laborum nostrum ipsa maxime. Voluptates et ut facere natus enim asperiores eos aut qui. Voluptatem nihil nesciunt consequatur sed in odit et a inventore.\n\nAut aut vel odit assumenda sunt. Sint ea ducimus id quia aut dolores est. Reiciendis iste ut est."
                        },
                        new
                        {
                            Id = 10,
                            ClientId = 14,
                            PetsitterId = 56,
                            Text = "Tempora iure neque. Sit nihil temporibus necessitatibus. Velit autem rerum sit neque modi est iusto recusandae. Nihil est eaque ea impedit temporibus aut. In quo consequatur expedita occaecati quis enim debitis.\n\nQui sit reiciendis expedita nulla ex mollitia quia delectus tenetur. Suscipit sunt suscipit ut et eaque nihil consectetur accusantium. Nihil non repellendus reprehenderit dolor in. At ut repudiandae quis voluptas pariatur voluptatibus id omnis.\n\nNobis omnis officia qui voluptatem eum veritatis eos doloremque. Mollitia suscipit nulla nobis aliquid totam accusantium sed adipisci. Libero a voluptas ut optio.\n\nQuos est aliquid ullam consequatur doloribus qui. Ut accusamus animi consectetur a voluptas eaque. Alias quaerat recusandae et id."
                        },
                        new
                        {
                            Id = 11,
                            ClientId = 12,
                            PetsitterId = 45,
                            Text = "Ea dolor ipsum est et voluptatem. Voluptatibus corporis sunt. Cum blanditiis tempora nisi voluptatem dolor. Animi nihil molestiae. Itaque harum officia voluptas. Voluptas aut sint.\n\nQui vel aut non velit. Ut omnis voluptatum non et facere fuga est unde. Deserunt et molestiae. Dolor provident iste sed voluptas ut. Beatae enim ea consequatur. Sunt et veniam rerum numquam magni.\n\nQuod ab hic porro qui sit. Ut exercitationem reiciendis. Ipsum quos mollitia similique. Aliquam saepe quis officiis facilis ut labore sed quia. Sit natus voluptate et vel. Hic doloremque nam qui qui voluptas.\n\nProvident ut repellendus sit amet fugiat necessitatibus reiciendis. Esse iure quia omnis reiciendis facere. Consequatur eum molestias voluptatem alias ducimus. Iure neque quo eius laudantium recusandae. Veniam velit ea quo laboriosam voluptate deleniti voluptates non."
                        },
                        new
                        {
                            Id = 12,
                            ClientId = 12,
                            PetsitterId = 42,
                            Text = "Doloribus occaecati quos. Aut ad amet et facere sit numquam et. Quod qui ipsum.\n\nMolestiae quae nam dolores aut delectus quae. Ut asperiores ut ut eos earum et iure. Accusamus tempore perferendis dolore amet maxime repudiandae. Beatae qui inventore magnam nam vitae quod.\n\nHic nesciunt qui at unde cupiditate et sit non. Voluptatem at adipisci ad. Optio ut non dolores laudantium consequatur et corporis placeat. Saepe qui maiores reprehenderit soluta voluptates neque.\n\nAsperiores rerum asperiores et quia ratione. Sint aliquam unde necessitatibus cum. Accusamus quia omnis molestiae iste et asperiores iure impedit vero. Dolore et nihil nam earum dolore veniam eos."
                        },
                        new
                        {
                            Id = 13,
                            ClientId = 25,
                            PetsitterId = 43,
                            Text = "Nihil qui sed aliquid. Qui maiores facere. Non consequatur tenetur dolor quo aliquam ex sint qui. Veniam repellendus ut voluptate libero odio eligendi reiciendis aut ut.\n\nArchitecto officia asperiores nulla nulla. Necessitatibus necessitatibus itaque quisquam aut. Ipsam est facere rerum aut asperiores non earum tenetur.\n\nNihil ea quia provident voluptates velit voluptatum reiciendis corrupti eum. Recusandae commodi repellendus doloribus velit repellat doloremque error. Error nobis natus. Voluptatem est consequatur. Perferendis suscipit dicta enim aliquam officia similique corrupti libero. Reiciendis deleniti laudantium maxime et a est quo iure.\n\nQui non repudiandae. Omnis iusto quod quibusdam vitae molestias. Animi animi sapiente voluptatem."
                        },
                        new
                        {
                            Id = 14,
                            ClientId = 11,
                            PetsitterId = 53,
                            Text = "Eius quas quod dolor ab dicta deserunt illum et. Dignissimos enim ullam quo omnis et voluptate. Et quos sequi eum. Officia enim possimus debitis eos repellendus totam numquam. Aperiam laborum aut est voluptas.\n\nNemo dolorem et cum consectetur quidem velit et necessitatibus. Non quod error et amet dolorum iure consequatur sequi. Nostrum quia minus aperiam mollitia reprehenderit qui ad est. Voluptatem deserunt expedita ipsam laborum quia ut sequi et. Fugit quo doloribus voluptatem aliquam qui est accusamus nulla asperiores. Et nobis necessitatibus similique aut iusto.\n\nEt dolores et. Inventore nobis recusandae dicta. Illum eos beatae ut nemo. Placeat blanditiis eius impedit. Accusamus quod ad molestiae eligendi laboriosam aliquid et voluptas.\n\nNecessitatibus tenetur architecto cumque blanditiis consectetur id. Suscipit quia rerum in ab maiores repudiandae aliquam quos deleniti. Fugit aut qui consequatur. Veritatis eius dolores ut. Suscipit doloremque voluptatem quas nemo aut consequuntur neque."
                        },
                        new
                        {
                            Id = 15,
                            ClientId = 23,
                            PetsitterId = 49,
                            Text = "Quis quis blanditiis incidunt laboriosam tempora dignissimos omnis vitae. Molestiae et harum et nesciunt ratione et quidem labore. Et non alias nostrum voluptatem saepe quod perferendis. Explicabo rerum qui in voluptatem mollitia ex ex reiciendis. Doloribus ab omnis quidem voluptatum id eligendi officiis.\n\nVoluptatibus exercitationem ut sint et repellendus architecto consequatur neque. Dignissimos atque et doloribus doloribus aut optio ab consequatur aperiam. Autem necessitatibus sint dolore facilis corporis in non est. Voluptatem et velit consequatur et sint numquam quo. Occaecati doloribus consectetur et minima quas.\n\nEst et et rerum molestias facilis aut amet ea. Ut eius atque. Voluptas rem minima nihil quam incidunt. Amet inventore atque laboriosam. Sint vel animi qui quidem quod accusantium non non doloremque.\n\nSint quam consectetur dolorum in eos rerum dolores asperiores voluptatem. Quisquam repellendus vero vitae. Deserunt praesentium odio nihil corporis dolorum. Adipisci officia culpa esse. Consectetur a similique vel est nostrum voluptates. Ipsa natus temporibus."
                        });
                });

            modelBuilder.Entity("PetSupport.Core.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Tabitha81@gmail.com",
                            Name = "Tabitha",
                            PhoneNumber = "(367) 863-7564 x5861",
                            Surname = "Marquardt"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Clifton.Metz@yahoo.com",
                            Name = "Clifton",
                            PhoneNumber = "1-637-392-0725 x0811",
                            Surname = "Metz"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Rosa58@yahoo.com",
                            Name = "Rosa",
                            PhoneNumber = "(205) 555-6609 x520",
                            Surname = "Braun"
                        },
                        new
                        {
                            Id = 4,
                            Email = "Salvatore.Luettgen41@hotmail.com",
                            Name = "Salvatore",
                            PhoneNumber = "833-734-8284 x85146",
                            Surname = "Luettgen"
                        },
                        new
                        {
                            Id = 5,
                            Email = "Dixie_Erdman98@hotmail.com",
                            Name = "Dixie",
                            PhoneNumber = "957-710-3185 x1359",
                            Surname = "Erdman"
                        },
                        new
                        {
                            Id = 6,
                            Email = "Calvin48@hotmail.com",
                            Name = "Calvin",
                            PhoneNumber = "970.985.5294 x882",
                            Surname = "Weber"
                        },
                        new
                        {
                            Id = 7,
                            Email = "June36@gmail.com",
                            Name = "June",
                            PhoneNumber = "338-637-6082 x77943",
                            Surname = "O'Keefe"
                        },
                        new
                        {
                            Id = 8,
                            Email = "Arlene_Rosenbaum82@yahoo.com",
                            Name = "Arlene",
                            PhoneNumber = "1-836-723-4030 x629",
                            Surname = "Rosenbaum"
                        },
                        new
                        {
                            Id = 9,
                            Email = "Lila.Murphy55@hotmail.com",
                            Name = "Lila",
                            PhoneNumber = "(575) 708-6262 x7984",
                            Surname = "Murphy"
                        },
                        new
                        {
                            Id = 10,
                            Email = "Sammy.Terry@gmail.com",
                            Name = "Sammy",
                            PhoneNumber = "451-711-4431 x68832",
                            Surname = "Terry"
                        },
                        new
                        {
                            Id = 11,
                            Email = "Felipe99@yahoo.com",
                            Name = "Felipe",
                            PhoneNumber = "1-443-765-5820",
                            Surname = "Bahringer"
                        },
                        new
                        {
                            Id = 12,
                            Email = "Tammy_Marquardt61@gmail.com",
                            Name = "Tammy",
                            PhoneNumber = "1-238-936-6451 x46634",
                            Surname = "Marquardt"
                        },
                        new
                        {
                            Id = 13,
                            Email = "Alfred.Murazik42@yahoo.com",
                            Name = "Alfred",
                            PhoneNumber = "(650) 663-3103",
                            Surname = "Murazik"
                        },
                        new
                        {
                            Id = 14,
                            Email = "Marcus_Hermiston@yahoo.com",
                            Name = "Marcus",
                            PhoneNumber = "1-368-503-9574 x1287",
                            Surname = "Hermiston"
                        },
                        new
                        {
                            Id = 15,
                            Email = "Nettie34@hotmail.com",
                            Name = "Nettie",
                            PhoneNumber = "(643) 801-8923",
                            Surname = "Will"
                        },
                        new
                        {
                            Id = 16,
                            Email = "Jesse_Bernier92@yahoo.com",
                            Name = "Jesse",
                            PhoneNumber = "413-632-5828 x16164",
                            Surname = "Bernier"
                        },
                        new
                        {
                            Id = 17,
                            Email = "Lucille_Veum20@gmail.com",
                            Name = "Lucille",
                            PhoneNumber = "1-664-385-3643",
                            Surname = "Veum"
                        },
                        new
                        {
                            Id = 18,
                            Email = "Muriel6@gmail.com",
                            Name = "Muriel",
                            PhoneNumber = "(909) 739-3988 x41259",
                            Surname = "Skiles"
                        },
                        new
                        {
                            Id = 19,
                            Email = "Thelma_VonRueden20@hotmail.com",
                            Name = "Thelma",
                            PhoneNumber = "228.838.8882 x1075",
                            Surname = "VonRueden"
                        },
                        new
                        {
                            Id = 20,
                            Email = "Dallas.Kuhic1@gmail.com",
                            Name = "Dallas",
                            PhoneNumber = "(614) 758-1162 x7491",
                            Surname = "Kuhic"
                        },
                        new
                        {
                            Id = 21,
                            Email = "Neal29@yahoo.com",
                            Name = "Neal",
                            PhoneNumber = "(419) 734-5333 x49286",
                            Surname = "Turner"
                        },
                        new
                        {
                            Id = 22,
                            Email = "Katherine_Cole61@yahoo.com",
                            Name = "Katherine",
                            PhoneNumber = "283.755.0135 x356",
                            Surname = "Cole"
                        },
                        new
                        {
                            Id = 23,
                            Email = "Patricia_Morar2@hotmail.com",
                            Name = "Patricia",
                            PhoneNumber = "(376) 631-4228",
                            Surname = "Morar"
                        },
                        new
                        {
                            Id = 24,
                            Email = "Mary_Crona@gmail.com",
                            Name = "Mary",
                            PhoneNumber = "(278) 458-0728 x2167",
                            Surname = "Crona"
                        },
                        new
                        {
                            Id = 25,
                            Email = "Chad78@hotmail.com",
                            Name = "Chad",
                            PhoneNumber = "787-410-9624 x667",
                            Surname = "Koss"
                        },
                        new
                        {
                            Id = 26,
                            Email = "Leah_Steuber@yahoo.com",
                            Name = "Leah",
                            PhoneNumber = "646.777.6076 x844",
                            Surname = "Steuber"
                        },
                        new
                        {
                            Id = 27,
                            Email = "Irene.Upton@yahoo.com",
                            Name = "Irene",
                            PhoneNumber = "(663) 715-6865 x8054",
                            Surname = "Upton"
                        },
                        new
                        {
                            Id = 28,
                            Email = "Tracy.Thompson@yahoo.com",
                            Name = "Tracy",
                            PhoneNumber = "1-282-558-9912 x302",
                            Surname = "Thompson"
                        },
                        new
                        {
                            Id = 29,
                            Email = "Jean58@yahoo.com",
                            Name = "Jean",
                            PhoneNumber = "667-907-0061 x783",
                            Surname = "Olson"
                        },
                        new
                        {
                            Id = 30,
                            Email = "Viola_Becker31@yahoo.com",
                            Name = "Viola",
                            PhoneNumber = "818.996.3457",
                            Surname = "Becker"
                        });
                });

            modelBuilder.Entity("PetSupport.Core.Entities.Petsitter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Petsitters");

                    b.HasData(
                        new
                        {
                            Id = 31,
                            Address = "Frederik Heights",
                            City = "West Ellen",
                            Description = "Enim tempore et aut labore repellendus officia ut omnis voluptate beatae voluptas quam non animi dolor et repellendus id aut quisquam ullam officiis ad dolores dolor cumque aut ab et.",
                            Email = "Andrew_Bogan31@hotmail.com",
                            Name = "Andrew",
                            Password = "bde4b865-eb27-44ca-8ad1-68511a4efb90",
                            PhoneNumber = "910-546-9101 x100",
                            PhotoId = "https://picsum.photos/640/480/?image=1033",
                            Surname = "Bogan"
                        },
                        new
                        {
                            Id = 32,
                            Address = "Brakus Union",
                            City = "North Cierrabury",
                            Description = "Officia ea et molestias delectus aut sint qui numquam maxime molestias nam eveniet numquam et omnis enim odit ea pariatur nam est quidem voluptas numquam consequuntur qui ducimus reprehenderit sed.",
                            Email = "Alberto_Gutmann@yahoo.com",
                            Name = "Alberto",
                            Password = "baadd236-05e4-4a30-9b3f-1e388900fe17",
                            PhoneNumber = "950-285-6007",
                            PhotoId = "https://picsum.photos/640/480/?image=739",
                            Surname = "Gutmann"
                        },
                        new
                        {
                            Id = 33,
                            Address = "Dibbert Falls",
                            City = "Elimouth",
                            Description = "Nisi accusamus asperiores perferendis praesentium nisi qui eius sed et sed et harum assumenda amet et quasi tempore blanditiis iste dolorem omnis magnam atque eum temporibus velit ipsum debitis quia.",
                            Email = "Felipe_Leannon@gmail.com",
                            Name = "Felipe",
                            Password = "e35f2bec-2255-4b3a-b6f5-8c55a5a82c7f",
                            PhoneNumber = "(208) 670-2820",
                            PhotoId = "https://picsum.photos/640/480/?image=767",
                            Surname = "Leannon"
                        },
                        new
                        {
                            Id = 34,
                            Address = "Roscoe Prairie",
                            City = "Keeleyborough",
                            Description = "Earum aperiam ex at quo et voluptatem mollitia quasi vero impedit esse ab voluptatibus et dolorum officia debitis aut et sapiente officiis officia quasi ut maiores molestias ea reiciendis nobis.",
                            Email = "Meghan.Gleason92@gmail.com",
                            Name = "Meghan",
                            Password = "3b764cef-ada7-47ff-8b12-57502fbb4655",
                            PhoneNumber = "(897) 676-5661",
                            PhotoId = "https://picsum.photos/640/480/?image=779",
                            Surname = "Gleason"
                        },
                        new
                        {
                            Id = 35,
                            Address = "Trinity Hollow",
                            City = "Bartellberg",
                            Description = "Repudiandae dolor minus nam ex sed quas officia facere aspernatur velit quia dolorum qui minus minima suscipit a maiores quidem et quia quis deleniti qui in provident in ipsam libero.",
                            Email = "Sara41@hotmail.com",
                            Name = "Sara",
                            Password = "4e45cc7d-ef1b-4231-bb9a-d9ce8ba13941",
                            PhoneNumber = "1-468-390-4298",
                            PhotoId = "https://picsum.photos/640/480/?image=417",
                            Surname = "Bins"
                        },
                        new
                        {
                            Id = 36,
                            Address = "Wyman Crescent",
                            City = "Watersport",
                            Description = "Aut dolores repudiandae in eius sapiente accusamus nostrum qui provident pariatur animi porro fuga quia placeat pariatur praesentium consequuntur ut maxime quia in reprehenderit blanditiis id et tempore accusantium vel.",
                            Email = "Suzanne.Dietrich93@yahoo.com",
                            Name = "Suzanne",
                            Password = "6d57893d-bd71-49d8-a3db-1efd6e5e5b61",
                            PhoneNumber = "1-857-682-8761 x207",
                            PhotoId = "https://picsum.photos/640/480/?image=991",
                            Surname = "Dietrich"
                        },
                        new
                        {
                            Id = 37,
                            Address = "Lynch Land",
                            City = "Dickinsonhaven",
                            Description = "Et molestiae enim excepturi dolor quia quae qui perferendis accusamus veniam enim eos cupiditate minima veniam aut animi non at ad magnam consequatur hic atque non voluptatem aut non iure.",
                            Email = "Bethany77@hotmail.com",
                            Name = "Bethany",
                            Password = "8033b810-808c-456a-943e-5d9f370e261b",
                            PhoneNumber = "777-319-0516",
                            PhotoId = "https://picsum.photos/640/480/?image=826",
                            Surname = "Mann"
                        },
                        new
                        {
                            Id = 38,
                            Address = "Frami Camp",
                            City = "West Melba",
                            Description = "Eos eligendi aliquid ut sequi sint velit nostrum aut dolores veritatis ab quidem sint dolor culpa non qui aut praesentium aut laborum molestias vitae magni quidem consequuntur accusamus nesciunt consequatur.",
                            Email = "Joshua76@yahoo.com",
                            Name = "Joshua",
                            Password = "353108b4-8f4b-4a14-9bc2-dedc9b78a821",
                            PhoneNumber = "425-564-3060 x20613",
                            PhotoId = "https://picsum.photos/640/480/?image=442",
                            Surname = "Wisozk"
                        },
                        new
                        {
                            Id = 39,
                            Address = "Purdy Inlet",
                            City = "East Jesus",
                            Description = "Deserunt voluptatem eligendi omnis labore amet quia accusamus veritatis et deserunt voluptatum iusto aliquam ut rerum recusandae debitis voluptas porro magni fugit molestiae aut consequuntur deleniti et ex qui eum.",
                            Email = "Melba15@gmail.com",
                            Name = "Melba",
                            Password = "c77b43f0-2158-454f-a46c-c69ea4900a02",
                            PhoneNumber = "(866) 821-2153 x5170",
                            PhotoId = "https://picsum.photos/640/480/?image=721",
                            Surname = "Littel"
                        },
                        new
                        {
                            Id = 40,
                            Address = "Imani Wall",
                            City = "Lake Alfredaville",
                            Description = "Cumque magni commodi dolores praesentium dolorem ratione reprehenderit ipsam id dolores officiis ut tempore reiciendis laudantium praesentium aut vitae saepe qui asperiores voluptatibus sit non neque consequatur exercitationem expedita laboriosam.",
                            Email = "Marcella.McDermott@yahoo.com",
                            Name = "Marcella",
                            Password = "35ede398-f037-4043-b72b-e9eedeaf828a",
                            PhoneNumber = "840.445.7673 x822",
                            PhotoId = "https://picsum.photos/640/480/?image=152",
                            Surname = "McDermott"
                        },
                        new
                        {
                            Id = 41,
                            Address = "Ortiz Fields",
                            City = "South Rod",
                            Description = "Quaerat nisi maiores praesentium voluptas quisquam occaecati accusantium et vero numquam ad doloribus aut aspernatur est delectus sunt omnis temporibus iure nisi assumenda accusantium voluptatum aliquam expedita iusto ipsam delectus.",
                            Email = "Mandy63@gmail.com",
                            Name = "Mandy",
                            Password = "3db5a3f2-ee41-4ad9-9863-6686f76a0f45",
                            PhoneNumber = "(587) 711-2218 x7949",
                            PhotoId = "https://picsum.photos/640/480/?image=712",
                            Surname = "Kuhn"
                        },
                        new
                        {
                            Id = 42,
                            Address = "Fahey Creek",
                            City = "Lebsackbury",
                            Description = "Autem facere maiores sequi et est qui quaerat dolores possimus atque qui officia provident consequatur in odit aut et exercitationem temporibus omnis culpa similique eveniet laboriosam labore officiis qui maxime.",
                            Email = "Juan_Lindgren57@gmail.com",
                            Name = "Juan",
                            Password = "4199f26c-1cb1-4765-baea-57a63eaad321",
                            PhoneNumber = "1-332-495-9950",
                            PhotoId = "https://picsum.photos/640/480/?image=574",
                            Surname = "Lindgren"
                        },
                        new
                        {
                            Id = 43,
                            Address = "Zita Locks",
                            City = "West Erich",
                            Description = "Quia rem quaerat voluptas fugiat ut et et est alias animi ratione amet asperiores hic omnis fuga reiciendis optio nam perferendis et illo inventore omnis ullam qui similique possimus ut.",
                            Email = "Vicki.Hermann52@hotmail.com",
                            Name = "Vicki",
                            Password = "b816aaae-cc89-4165-9afb-c518a1e558df",
                            PhoneNumber = "426.370.1424",
                            PhotoId = "https://picsum.photos/640/480/?image=441",
                            Surname = "Hermann"
                        },
                        new
                        {
                            Id = 44,
                            Address = "Jaylin Bridge",
                            City = "Port Alfside",
                            Description = "Officia saepe et aut sapiente recusandae esse nihil et accusamus ut unde tenetur beatae asperiores architecto ipsa quaerat quis pariatur iure dolorem quia blanditiis cumque eveniet quas repellendus qui voluptas.",
                            Email = "Maggie_Lynch19@gmail.com",
                            Name = "Maggie",
                            Password = "f1595b02-209f-44f1-8644-ee1e9a82cb18",
                            PhoneNumber = "406.952.4175 x53315",
                            PhotoId = "https://picsum.photos/640/480/?image=659",
                            Surname = "Lynch"
                        },
                        new
                        {
                            Id = 45,
                            Address = "Shayne Spurs",
                            City = "Lake Emmet",
                            Description = "Quia cumque aperiam ducimus id autem est at fuga qui voluptas occaecati sint praesentium itaque eos eligendi rerum aut saepe aut est excepturi aut rerum cupiditate dicta velit deleniti et.",
                            Email = "Joanna49@yahoo.com",
                            Name = "Joanna",
                            Password = "38f04561-4bf9-4cac-8536-f76e69cae2bd",
                            PhoneNumber = "1-808-547-7104 x633",
                            PhotoId = "https://picsum.photos/640/480/?image=934",
                            Surname = "Smith"
                        },
                        new
                        {
                            Id = 46,
                            Address = "Padberg Locks",
                            City = "Lake Brigitte",
                            Description = "Labore veniam velit sit et architecto temporibus consequatur sit ab aliquam aut expedita quia et aut aliquam inventore ea occaecati rerum nemo voluptatem deleniti ea voluptatem nobis sed repellat iusto.",
                            Email = "Pat_Sipes92@yahoo.com",
                            Name = "Pat",
                            Password = "6d250e1e-51e5-4a00-83e0-aacad15a4025",
                            PhoneNumber = "213-551-2827 x53794",
                            PhotoId = "https://picsum.photos/640/480/?image=226",
                            Surname = "Sipes"
                        },
                        new
                        {
                            Id = 47,
                            Address = "Jones Viaduct",
                            City = "Lake Milanshire",
                            Description = "Suscipit qui consectetur provident culpa eligendi ut reprehenderit omnis iste harum pariatur ipsam et quos itaque et quia quo et voluptatem aut et ea odit velit sint perferendis corrupti et.",
                            Email = "Melissa23@gmail.com",
                            Name = "Melissa",
                            Password = "46b86928-bf7a-4b61-8f74-445e60a9da64",
                            PhoneNumber = "539.692.7953",
                            PhotoId = "https://picsum.photos/640/480/?image=254",
                            Surname = "Mueller"
                        },
                        new
                        {
                            Id = 48,
                            Address = "Mann Summit",
                            City = "Lake Montanafort",
                            Description = "Quas illum corporis veritatis voluptatem qui assumenda qui laborum quos dignissimos asperiores illo vero sequi distinctio asperiores sunt atque molestiae voluptatem vitae saepe autem et atque adipisci natus omnis architecto.",
                            Email = "Lucia64@yahoo.com",
                            Name = "Lucia",
                            Password = "5ea660f3-e3be-4351-9932-0fcf31aec99e",
                            PhoneNumber = "1-562-631-8417",
                            PhotoId = "https://picsum.photos/640/480/?image=50",
                            Surname = "Prosacco"
                        },
                        new
                        {
                            Id = 49,
                            Address = "Leannon Springs",
                            City = "Spencerville",
                            Description = "Excepturi est reiciendis itaque ut consequuntur similique illum aut a soluta eligendi doloribus dolores sed voluptate numquam distinctio deleniti blanditiis iusto consectetur et deleniti quis qui ratione qui rerum et.",
                            Email = "Lisa.Shields@hotmail.com",
                            Name = "Lisa",
                            Password = "2cb51276-9c6d-42ab-8e93-265ce06ef1d1",
                            PhoneNumber = "1-706-249-9186 x295",
                            PhotoId = "https://picsum.photos/640/480/?image=207",
                            Surname = "Shields"
                        },
                        new
                        {
                            Id = 50,
                            Address = "Kessler Track",
                            City = "Kesslerchester",
                            Description = "Perspiciatis amet inventore qui officiis nemo laudantium sunt in aliquid repudiandae a et ut aliquid inventore beatae voluptates reprehenderit amet aut laborum pariatur fuga ex sint omnis sapiente enim officia.",
                            Email = "Jeremy.Rohan85@gmail.com",
                            Name = "Jeremy",
                            Password = "e9459fc5-3a15-4821-870f-3e3cb0c89196",
                            PhoneNumber = "919-893-5464",
                            PhotoId = "https://picsum.photos/640/480/?image=694",
                            Surname = "Rohan"
                        },
                        new
                        {
                            Id = 51,
                            Address = "Israel Pine",
                            City = "Port Eloytown",
                            Description = "Et fugiat quaerat fuga tenetur voluptates quia dolores et officiis consequatur ullam cupiditate tenetur aut aspernatur corrupti ad repellat voluptatum explicabo vel possimus adipisci eaque temporibus quia et temporibus corporis.",
                            Email = "Gerald.Bergstrom70@gmail.com",
                            Name = "Gerald",
                            Password = "37b10bc5-6c90-4c08-b48f-041c7eee8924",
                            PhoneNumber = "929-589-3403",
                            PhotoId = "https://picsum.photos/640/480/?image=495",
                            Surname = "Bergstrom"
                        },
                        new
                        {
                            Id = 52,
                            Address = "Jamarcus Inlet",
                            City = "Estherborough",
                            Description = "Quam qui aliquid commodi debitis quis consequatur eum maiores voluptatem praesentium earum temporibus nisi architecto excepturi omnis magni voluptatem debitis reiciendis ea possimus voluptas nesciunt illo magni atque voluptatibus dolor.",
                            Email = "Margarita28@gmail.com",
                            Name = "Margarita",
                            Password = "39c72db8-427e-4175-8911-8059b0f98805",
                            PhoneNumber = "866-700-5155 x33473",
                            PhotoId = "https://picsum.photos/640/480/?image=0",
                            Surname = "O'Conner"
                        },
                        new
                        {
                            Id = 53,
                            Address = "Baumbach Parkways",
                            City = "Elsafort",
                            Description = "Ut esse sed impedit et dolorem exercitationem molestias quod ea nulla ad fugit quia et nihil eligendi ducimus consectetur iusto voluptate iure non in voluptas earum eius iure perferendis quos.",
                            Email = "Maxine_Boyle@gmail.com",
                            Name = "Maxine",
                            Password = "0e98ad13-3593-404a-a927-68f3b9978f77",
                            PhoneNumber = "(491) 530-0528",
                            PhotoId = "https://picsum.photos/640/480/?image=743",
                            Surname = "Boyle"
                        },
                        new
                        {
                            Id = 54,
                            Address = "Kunde Rest",
                            City = "Brownville",
                            Description = "Et et et voluptate aperiam labore optio corrupti consequatur itaque natus saepe error omnis voluptas consequatur amet sit minima aperiam facere quia qui voluptas numquam et officiis optio fugit ducimus.",
                            Email = "Roxanne.Schulist90@yahoo.com",
                            Name = "Roxanne",
                            Password = "15a59d77-9c91-402a-b2a7-157cb9b95d00",
                            PhoneNumber = "245.327.9869 x426",
                            PhotoId = "https://picsum.photos/640/480/?image=626",
                            Surname = "Schulist"
                        },
                        new
                        {
                            Id = 55,
                            Address = "Bogisich Plains",
                            City = "Koelpinhaven",
                            Description = "Iusto tenetur commodi itaque est eum consequatur nisi fugiat atque dolores voluptate ipsa incidunt quia perferendis excepturi beatae doloribus labore rerum voluptas nihil eveniet in quidem aut esse nihil enim.",
                            Email = "Kendra_Morar28@yahoo.com",
                            Name = "Kendra",
                            Password = "9120caf5-1067-417c-8943-48eeac2d230a",
                            PhoneNumber = "(962) 314-0712",
                            PhotoId = "https://picsum.photos/640/480/?image=353",
                            Surname = "Morar"
                        },
                        new
                        {
                            Id = 56,
                            Address = "Schamberger Station",
                            City = "Lenoraborough",
                            Description = "Laudantium cum nobis possimus hic quia incidunt placeat quasi doloribus quasi cupiditate est perferendis iste explicabo vitae fugiat in et nesciunt quo non cum labore velit nihil itaque amet esse.",
                            Email = "Estelle_Lind@hotmail.com",
                            Name = "Estelle",
                            Password = "014eebfe-3f1d-4837-8279-05d342e49e11",
                            PhoneNumber = "1-663-715-4500 x565",
                            PhotoId = "https://picsum.photos/640/480/?image=515",
                            Surname = "Lind"
                        },
                        new
                        {
                            Id = 57,
                            Address = "Heaney Plain",
                            City = "Schmelerburgh",
                            Description = "Nostrum iusto porro illum voluptates ullam minima ipsam sit architecto pariatur quia non qui nihil odio corrupti alias doloremque nihil illum quidem in et quia necessitatibus doloremque ullam temporibus adipisci.",
                            Email = "Angelica.Kertzmann42@yahoo.com",
                            Name = "Angelica",
                            Password = "3aa5f749-fabf-4c73-8546-341b8d62d94d",
                            PhoneNumber = "894-574-0578 x25654",
                            PhotoId = "https://picsum.photos/640/480/?image=33",
                            Surname = "Kertzmann"
                        },
                        new
                        {
                            Id = 58,
                            Address = "Jones Coves",
                            City = "Meganefort",
                            Description = "Ut quaerat sint ea et nihil eos eos deleniti tenetur non totam facilis voluptatem ullam atque quos natus placeat mollitia quaerat dolor aut dolores numquam minima quo debitis facilis provident.",
                            Email = "Holly_Rempel@gmail.com",
                            Name = "Holly",
                            Password = "9466e24e-bce1-43c8-9c4b-a68b0a58f4ab",
                            PhoneNumber = "1-870-666-8960 x2958",
                            PhotoId = "https://picsum.photos/640/480/?image=310",
                            Surname = "Rempel"
                        },
                        new
                        {
                            Id = 59,
                            Address = "Schiller Haven",
                            City = "Hayeschester",
                            Description = "Cum aut voluptatibus et veritatis quam et deserunt quia voluptatem magni placeat et hic dicta consectetur natus dignissimos sed voluptatibus commodi ad fugiat voluptatem cumque vitae vel maxime est est.",
                            Email = "Leona86@hotmail.com",
                            Name = "Leona",
                            Password = "6c77a083-0f44-4ea1-a75b-13f2227f2fe2",
                            PhoneNumber = "1-293-543-7165",
                            PhotoId = "https://picsum.photos/640/480/?image=541",
                            Surname = "Ruecker"
                        },
                        new
                        {
                            Id = 60,
                            Address = "Liza Expressway",
                            City = "Lindgrenshire",
                            Description = "Blanditiis quidem accusantium dolorem blanditiis voluptatem ullam facere sit mollitia et placeat iusto est ratione eos molestiae est quas aut explicabo quisquam reprehenderit quos libero enim necessitatibus delectus est ex.",
                            Email = "Louise.Rath13@yahoo.com",
                            Name = "Louise",
                            Password = "4a7b5118-4d12-42a0-a42c-59f694963379",
                            PhoneNumber = "920-543-2999 x64945",
                            PhotoId = "https://picsum.photos/640/480/?image=380",
                            Surname = "Rath"
                        });
                });

            modelBuilder.Entity("PetSupport.Core.Entities.PetsitterService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("PetsitterId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PetsitterId");

                    b.HasIndex("ServiceId");

                    b.ToTable("PetSupportServices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PetsitterId = 42,
                            Price = 56.0,
                            ServiceId = 2
                        },
                        new
                        {
                            Id = 2,
                            PetsitterId = 46,
                            Price = 40.0,
                            ServiceId = 13
                        },
                        new
                        {
                            Id = 3,
                            PetsitterId = 44,
                            Price = 128.0,
                            ServiceId = 28
                        },
                        new
                        {
                            Id = 4,
                            PetsitterId = 32,
                            Price = 92.0,
                            ServiceId = 6
                        },
                        new
                        {
                            Id = 5,
                            PetsitterId = 41,
                            Price = 123.0,
                            ServiceId = 25
                        },
                        new
                        {
                            Id = 6,
                            PetsitterId = 45,
                            Price = 35.0,
                            ServiceId = 7
                        },
                        new
                        {
                            Id = 7,
                            PetsitterId = 53,
                            Price = 94.0,
                            ServiceId = 8
                        },
                        new
                        {
                            Id = 8,
                            PetsitterId = 45,
                            Price = 61.0,
                            ServiceId = 5
                        },
                        new
                        {
                            Id = 9,
                            PetsitterId = 41,
                            Price = 109.0,
                            ServiceId = 1
                        },
                        new
                        {
                            Id = 10,
                            PetsitterId = 38,
                            Price = 55.0,
                            ServiceId = 7
                        },
                        new
                        {
                            Id = 11,
                            PetsitterId = 45,
                            Price = 92.0,
                            ServiceId = 19
                        },
                        new
                        {
                            Id = 12,
                            PetsitterId = 59,
                            Price = 115.0,
                            ServiceId = 1
                        },
                        new
                        {
                            Id = 13,
                            PetsitterId = 39,
                            Price = 110.0,
                            ServiceId = 14
                        },
                        new
                        {
                            Id = 14,
                            PetsitterId = 50,
                            Price = 99.0,
                            ServiceId = 29
                        },
                        new
                        {
                            Id = 15,
                            PetsitterId = 56,
                            Price = 113.0,
                            ServiceId = 8
                        },
                        new
                        {
                            Id = 16,
                            PetsitterId = 44,
                            Price = 96.0,
                            ServiceId = 11
                        },
                        new
                        {
                            Id = 17,
                            PetsitterId = 48,
                            Price = 69.0,
                            ServiceId = 12
                        },
                        new
                        {
                            Id = 18,
                            PetsitterId = 58,
                            Price = 76.0,
                            ServiceId = 12
                        },
                        new
                        {
                            Id = 19,
                            PetsitterId = 50,
                            Price = 140.0,
                            ServiceId = 27
                        },
                        new
                        {
                            Id = 20,
                            PetsitterId = 59,
                            Price = 78.0,
                            ServiceId = 6
                        },
                        new
                        {
                            Id = 21,
                            PetsitterId = 43,
                            Price = 115.0,
                            ServiceId = 7
                        },
                        new
                        {
                            Id = 22,
                            PetsitterId = 49,
                            Price = 100.0,
                            ServiceId = 18
                        },
                        new
                        {
                            Id = 23,
                            PetsitterId = 60,
                            Price = 123.0,
                            ServiceId = 13
                        },
                        new
                        {
                            Id = 24,
                            PetsitterId = 33,
                            Price = 123.0,
                            ServiceId = 6
                        },
                        new
                        {
                            Id = 25,
                            PetsitterId = 42,
                            Price = 67.0,
                            ServiceId = 4
                        },
                        new
                        {
                            Id = 26,
                            PetsitterId = 59,
                            Price = 138.0,
                            ServiceId = 20
                        },
                        new
                        {
                            Id = 27,
                            PetsitterId = 48,
                            Price = 111.0,
                            ServiceId = 27
                        },
                        new
                        {
                            Id = 28,
                            PetsitterId = 34,
                            Price = 130.0,
                            ServiceId = 21
                        },
                        new
                        {
                            Id = 29,
                            PetsitterId = 57,
                            Price = 59.0,
                            ServiceId = 18
                        },
                        new
                        {
                            Id = 30,
                            PetsitterId = 35,
                            Price = 46.0,
                            ServiceId = 9
                        },
                        new
                        {
                            Id = 31,
                            PetsitterId = 54,
                            Price = 60.0,
                            ServiceId = 11
                        },
                        new
                        {
                            Id = 32,
                            PetsitterId = 38,
                            Price = 118.0,
                            ServiceId = 7
                        },
                        new
                        {
                            Id = 33,
                            PetsitterId = 57,
                            Price = 110.0,
                            ServiceId = 8
                        },
                        new
                        {
                            Id = 34,
                            PetsitterId = 34,
                            Price = 143.0,
                            ServiceId = 14
                        },
                        new
                        {
                            Id = 35,
                            PetsitterId = 54,
                            Price = 53.0,
                            ServiceId = 16
                        },
                        new
                        {
                            Id = 36,
                            PetsitterId = 47,
                            Price = 63.0,
                            ServiceId = 17
                        },
                        new
                        {
                            Id = 37,
                            PetsitterId = 33,
                            Price = 60.0,
                            ServiceId = 22
                        },
                        new
                        {
                            Id = 38,
                            PetsitterId = 31,
                            Price = 68.0,
                            ServiceId = 12
                        },
                        new
                        {
                            Id = 39,
                            PetsitterId = 52,
                            Price = 95.0,
                            ServiceId = 10
                        },
                        new
                        {
                            Id = 40,
                            PetsitterId = 57,
                            Price = 31.0,
                            ServiceId = 22
                        },
                        new
                        {
                            Id = 41,
                            PetsitterId = 41,
                            Price = 46.0,
                            ServiceId = 26
                        },
                        new
                        {
                            Id = 42,
                            PetsitterId = 50,
                            Price = 132.0,
                            ServiceId = 9
                        },
                        new
                        {
                            Id = 43,
                            PetsitterId = 46,
                            Price = 137.0,
                            ServiceId = 4
                        },
                        new
                        {
                            Id = 44,
                            PetsitterId = 48,
                            Price = 79.0,
                            ServiceId = 3
                        },
                        new
                        {
                            Id = 45,
                            PetsitterId = 38,
                            Price = 82.0,
                            ServiceId = 14
                        },
                        new
                        {
                            Id = 46,
                            PetsitterId = 52,
                            Price = 49.0,
                            ServiceId = 11
                        },
                        new
                        {
                            Id = 47,
                            PetsitterId = 50,
                            Price = 35.0,
                            ServiceId = 11
                        },
                        new
                        {
                            Id = 48,
                            PetsitterId = 59,
                            Price = 100.0,
                            ServiceId = 2
                        },
                        new
                        {
                            Id = 49,
                            PetsitterId = 57,
                            Price = 144.0,
                            ServiceId = 24
                        },
                        new
                        {
                            Id = 50,
                            PetsitterId = 59,
                            Price = 138.0,
                            ServiceId = 16
                        },
                        new
                        {
                            Id = 51,
                            PetsitterId = 36,
                            Price = 92.0,
                            ServiceId = 30
                        },
                        new
                        {
                            Id = 52,
                            PetsitterId = 50,
                            Price = 101.0,
                            ServiceId = 23
                        },
                        new
                        {
                            Id = 53,
                            PetsitterId = 55,
                            Price = 58.0,
                            ServiceId = 4
                        },
                        new
                        {
                            Id = 54,
                            PetsitterId = 41,
                            Price = 81.0,
                            ServiceId = 1
                        },
                        new
                        {
                            Id = 55,
                            PetsitterId = 42,
                            Price = 106.0,
                            ServiceId = 15
                        },
                        new
                        {
                            Id = 56,
                            PetsitterId = 56,
                            Price = 141.0,
                            ServiceId = 24
                        },
                        new
                        {
                            Id = 57,
                            PetsitterId = 57,
                            Price = 147.0,
                            ServiceId = 30
                        },
                        new
                        {
                            Id = 58,
                            PetsitterId = 42,
                            Price = 77.0,
                            ServiceId = 7
                        },
                        new
                        {
                            Id = 59,
                            PetsitterId = 60,
                            Price = 126.0,
                            ServiceId = 12
                        },
                        new
                        {
                            Id = 60,
                            PetsitterId = 47,
                            Price = 90.0,
                            ServiceId = 24
                        },
                        new
                        {
                            Id = 61,
                            PetsitterId = 58,
                            Price = 100.0,
                            ServiceId = 18
                        },
                        new
                        {
                            Id = 62,
                            PetsitterId = 60,
                            Price = 39.0,
                            ServiceId = 12
                        },
                        new
                        {
                            Id = 63,
                            PetsitterId = 57,
                            Price = 114.0,
                            ServiceId = 18
                        },
                        new
                        {
                            Id = 64,
                            PetsitterId = 56,
                            Price = 56.0,
                            ServiceId = 28
                        },
                        new
                        {
                            Id = 65,
                            PetsitterId = 58,
                            Price = 68.0,
                            ServiceId = 10
                        },
                        new
                        {
                            Id = 66,
                            PetsitterId = 49,
                            Price = 97.0,
                            ServiceId = 18
                        },
                        new
                        {
                            Id = 67,
                            PetsitterId = 59,
                            Price = 30.0,
                            ServiceId = 2
                        },
                        new
                        {
                            Id = 68,
                            PetsitterId = 31,
                            Price = 94.0,
                            ServiceId = 2
                        },
                        new
                        {
                            Id = 69,
                            PetsitterId = 58,
                            Price = 122.0,
                            ServiceId = 25
                        },
                        new
                        {
                            Id = 70,
                            PetsitterId = 34,
                            Price = 75.0,
                            ServiceId = 21
                        },
                        new
                        {
                            Id = 71,
                            PetsitterId = 54,
                            Price = 72.0,
                            ServiceId = 8
                        },
                        new
                        {
                            Id = 72,
                            PetsitterId = 52,
                            Price = 81.0,
                            ServiceId = 14
                        },
                        new
                        {
                            Id = 73,
                            PetsitterId = 56,
                            Price = 44.0,
                            ServiceId = 12
                        },
                        new
                        {
                            Id = 74,
                            PetsitterId = 47,
                            Price = 54.0,
                            ServiceId = 29
                        },
                        new
                        {
                            Id = 75,
                            PetsitterId = 37,
                            Price = 39.0,
                            ServiceId = 2
                        },
                        new
                        {
                            Id = 76,
                            PetsitterId = 53,
                            Price = 141.0,
                            ServiceId = 14
                        },
                        new
                        {
                            Id = 77,
                            PetsitterId = 33,
                            Price = 126.0,
                            ServiceId = 11
                        },
                        new
                        {
                            Id = 78,
                            PetsitterId = 38,
                            Price = 118.0,
                            ServiceId = 19
                        },
                        new
                        {
                            Id = 79,
                            PetsitterId = 45,
                            Price = 95.0,
                            ServiceId = 27
                        },
                        new
                        {
                            Id = 80,
                            PetsitterId = 32,
                            Price = 99.0,
                            ServiceId = 3
                        },
                        new
                        {
                            Id = 81,
                            PetsitterId = 40,
                            Price = 136.0,
                            ServiceId = 24
                        },
                        new
                        {
                            Id = 82,
                            PetsitterId = 40,
                            Price = 110.0,
                            ServiceId = 2
                        },
                        new
                        {
                            Id = 83,
                            PetsitterId = 57,
                            Price = 134.0,
                            ServiceId = 6
                        },
                        new
                        {
                            Id = 84,
                            PetsitterId = 57,
                            Price = 53.0,
                            ServiceId = 24
                        },
                        new
                        {
                            Id = 85,
                            PetsitterId = 44,
                            Price = 41.0,
                            ServiceId = 12
                        },
                        new
                        {
                            Id = 86,
                            PetsitterId = 55,
                            Price = 30.0,
                            ServiceId = 25
                        },
                        new
                        {
                            Id = 87,
                            PetsitterId = 44,
                            Price = 73.0,
                            ServiceId = 6
                        },
                        new
                        {
                            Id = 88,
                            PetsitterId = 56,
                            Price = 71.0,
                            ServiceId = 2
                        },
                        new
                        {
                            Id = 89,
                            PetsitterId = 48,
                            Price = 108.0,
                            ServiceId = 17
                        },
                        new
                        {
                            Id = 90,
                            PetsitterId = 49,
                            Price = 97.0,
                            ServiceId = 7
                        });
                });

            modelBuilder.Entity("PetSupport.Core.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Name")
                        .HasColumnType("int");

                    b.Property<int>("Unit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Inventore animi aut consequatur pariatur.",
                            ImageId = "https://loremflickr.com/320/240?lock=1593273893",
                            Name = 3,
                            Unit = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Velit soluta ut vero voluptatum.",
                            ImageId = "https://loremflickr.com/320/240?lock=699112102",
                            Name = 0,
                            Unit = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "In aut accusantium inventore ad.",
                            ImageId = "https://loremflickr.com/320/240?lock=783108421",
                            Name = 0,
                            Unit = 2
                        },
                        new
                        {
                            Id = 4,
                            Description = "Soluta incidunt cum exercitationem amet.",
                            ImageId = "https://loremflickr.com/320/240?lock=1632747932",
                            Name = 3,
                            Unit = 0
                        },
                        new
                        {
                            Id = 5,
                            Description = "Aut et inventore ex aut.",
                            ImageId = "https://loremflickr.com/320/240?lock=20025034",
                            Name = 4,
                            Unit = 2
                        },
                        new
                        {
                            Id = 6,
                            Description = "Voluptas quia saepe earum est.",
                            ImageId = "https://loremflickr.com/320/240?lock=1733792009",
                            Name = 0,
                            Unit = 0
                        },
                        new
                        {
                            Id = 7,
                            Description = "Est alias quia ut nulla.",
                            ImageId = "https://loremflickr.com/320/240?lock=1387034100",
                            Name = 1,
                            Unit = 0
                        },
                        new
                        {
                            Id = 8,
                            Description = "Voluptatum ut quos doloribus debitis.",
                            ImageId = "https://loremflickr.com/320/240?lock=294141962",
                            Name = 0,
                            Unit = 2
                        },
                        new
                        {
                            Id = 9,
                            Description = "Delectus modi dolorem ratione dignissimos.",
                            ImageId = "https://loremflickr.com/320/240?lock=395229782",
                            Name = 3,
                            Unit = 0
                        },
                        new
                        {
                            Id = 10,
                            Description = "Porro quod quas totam alias.",
                            ImageId = "https://loremflickr.com/320/240?lock=1797499681",
                            Name = 1,
                            Unit = 0
                        },
                        new
                        {
                            Id = 11,
                            Description = "Dolores omnis inventore et et.",
                            ImageId = "https://loremflickr.com/320/240?lock=2109180396",
                            Name = 2,
                            Unit = 0
                        },
                        new
                        {
                            Id = 12,
                            Description = "Cumque pariatur dignissimos tenetur enim.",
                            ImageId = "https://loremflickr.com/320/240?lock=1957442382",
                            Name = 0,
                            Unit = 1
                        },
                        new
                        {
                            Id = 13,
                            Description = "Fugit laudantium natus aspernatur natus.",
                            ImageId = "https://loremflickr.com/320/240?lock=1522666881",
                            Name = 3,
                            Unit = 0
                        },
                        new
                        {
                            Id = 14,
                            Description = "Unde consequatur ut non accusantium.",
                            ImageId = "https://loremflickr.com/320/240?lock=1996233359",
                            Name = 4,
                            Unit = 1
                        },
                        new
                        {
                            Id = 15,
                            Description = "Qui aspernatur mollitia accusantium quia.",
                            ImageId = "https://loremflickr.com/320/240?lock=641503537",
                            Name = 2,
                            Unit = 0
                        },
                        new
                        {
                            Id = 16,
                            Description = "Necessitatibus omnis molestiae eaque ab.",
                            ImageId = "https://loremflickr.com/320/240?lock=992154566",
                            Name = 4,
                            Unit = 2
                        },
                        new
                        {
                            Id = 17,
                            Description = "Reiciendis qui eius necessitatibus consequatur.",
                            ImageId = "https://loremflickr.com/320/240?lock=1717711096",
                            Name = 4,
                            Unit = 1
                        },
                        new
                        {
                            Id = 18,
                            Description = "Dolore corrupti qui itaque omnis.",
                            ImageId = "https://loremflickr.com/320/240?lock=848024654",
                            Name = 0,
                            Unit = 0
                        },
                        new
                        {
                            Id = 19,
                            Description = "Dicta dicta eos quaerat accusantium.",
                            ImageId = "https://loremflickr.com/320/240?lock=16952326",
                            Name = 1,
                            Unit = 1
                        },
                        new
                        {
                            Id = 20,
                            Description = "Et molestias tenetur tempora laborum.",
                            ImageId = "https://loremflickr.com/320/240?lock=708858163",
                            Name = 1,
                            Unit = 0
                        },
                        new
                        {
                            Id = 21,
                            Description = "Voluptatem voluptas explicabo reiciendis illum.",
                            ImageId = "https://loremflickr.com/320/240?lock=433432689",
                            Name = 3,
                            Unit = 0
                        },
                        new
                        {
                            Id = 22,
                            Description = "Consequatur tenetur quia aliquam illo.",
                            ImageId = "https://loremflickr.com/320/240?lock=1251311857",
                            Name = 2,
                            Unit = 1
                        },
                        new
                        {
                            Id = 23,
                            Description = "Assumenda quisquam quis et unde.",
                            ImageId = "https://loremflickr.com/320/240?lock=1553377512",
                            Name = 3,
                            Unit = 0
                        },
                        new
                        {
                            Id = 24,
                            Description = "Sit voluptatem debitis est nisi.",
                            ImageId = "https://loremflickr.com/320/240?lock=679990157",
                            Name = 3,
                            Unit = 0
                        },
                        new
                        {
                            Id = 25,
                            Description = "Dolores odit enim sunt sunt.",
                            ImageId = "https://loremflickr.com/320/240?lock=1541424634",
                            Name = 4,
                            Unit = 0
                        },
                        new
                        {
                            Id = 26,
                            Description = "Ipsa et blanditiis officia omnis.",
                            ImageId = "https://loremflickr.com/320/240?lock=963023015",
                            Name = 0,
                            Unit = 0
                        },
                        new
                        {
                            Id = 27,
                            Description = "Consequatur quidem exercitationem illo laborum.",
                            ImageId = "https://loremflickr.com/320/240?lock=631340919",
                            Name = 3,
                            Unit = 0
                        },
                        new
                        {
                            Id = 28,
                            Description = "Id ea est beatae illum.",
                            ImageId = "https://loremflickr.com/320/240?lock=1379883833",
                            Name = 4,
                            Unit = 1
                        },
                        new
                        {
                            Id = 29,
                            Description = "Dolores soluta et quia non.",
                            ImageId = "https://loremflickr.com/320/240?lock=516374598",
                            Name = 2,
                            Unit = 0
                        },
                        new
                        {
                            Id = 30,
                            Description = "Enim deserunt et dolor ut.",
                            ImageId = "https://loremflickr.com/320/240?lock=1096849045",
                            Name = 2,
                            Unit = 1
                        });
                });

            modelBuilder.Entity("PetSupport.Core.Entities.BookingMessage", b =>
                {
                    b.HasOne("PetSupport.Core.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetSupport.Core.Entities.Petsitter", "Petsitter")
                        .WithMany()
                        .HasForeignKey("PetsitterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Petsitter");
                });

            modelBuilder.Entity("PetSupport.Core.Entities.PetsitterService", b =>
                {
                    b.HasOne("PetSupport.Core.Entities.Petsitter", "Petsitter")
                        .WithMany("Services")
                        .HasForeignKey("PetsitterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetSupport.Core.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Petsitter");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("PetSupport.Core.Entities.Petsitter", b =>
                {
                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
